(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

[@@@ocaml.warning "-33-27-26"]

open! Tf.Prelude

type cloudflare_access_ca_certificate = {
  account_id : string prop option; [@option]
      (** The account identifier to target for the resource. Conflicts with `zone_id`. *)
  application_id : string prop;
      (** The Access Application ID to associate with the CA certificate. *)
  id : string prop option; [@option]  (** id *)
  zone_id : string prop option; [@option]
      (** The zone identifier to target for the resource. Conflicts with `account_id`. *)
}
[@@deriving yojson_of]
(** Cloudflare Access can replace traditional SSH key models with
short-lived certificates issued to your users based on the token
generated by their Access login.
 *)

let cloudflare_access_ca_certificate ?account_id ?id ?zone_id
    ~application_id __resource_id =
  let __resource_type = "cloudflare_access_ca_certificate" in
  let __resource = { account_id; application_id; id; zone_id } in
  Resource.add ~type_:__resource_type ~id:__resource_id
    (yojson_of_cloudflare_access_ca_certificate __resource);
  ()
