(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type cloudflare_ruleset__rules__action_parameters__algorithms
type cloudflare_ruleset__rules__action_parameters__autominify
type cloudflare_ruleset__rules__action_parameters__browser_ttl

type cloudflare_ruleset__rules__action_parameters__cache_key__custom_key__cookie

type cloudflare_ruleset__rules__action_parameters__cache_key__custom_key__header

type cloudflare_ruleset__rules__action_parameters__cache_key__custom_key__host

type cloudflare_ruleset__rules__action_parameters__cache_key__custom_key__query_string

type cloudflare_ruleset__rules__action_parameters__cache_key__custom_key__user

type cloudflare_ruleset__rules__action_parameters__cache_key__custom_key

type cloudflare_ruleset__rules__action_parameters__cache_key

type cloudflare_ruleset__rules__action_parameters__edge_ttl__status_code_ttl__status_code_range

type cloudflare_ruleset__rules__action_parameters__edge_ttl__status_code_ttl

type cloudflare_ruleset__rules__action_parameters__edge_ttl
type cloudflare_ruleset__rules__action_parameters__from_list

type cloudflare_ruleset__rules__action_parameters__from_value__target_url

type cloudflare_ruleset__rules__action_parameters__from_value
type cloudflare_ruleset__rules__action_parameters__headers
type cloudflare_ruleset__rules__action_parameters__matched_data
type cloudflare_ruleset__rules__action_parameters__origin

type cloudflare_ruleset__rules__action_parameters__overrides__categories

type cloudflare_ruleset__rules__action_parameters__overrides__rules
type cloudflare_ruleset__rules__action_parameters__overrides
type cloudflare_ruleset__rules__action_parameters__response
type cloudflare_ruleset__rules__action_parameters__serve_stale
type cloudflare_ruleset__rules__action_parameters__sni
type cloudflare_ruleset__rules__action_parameters__uri__path
type cloudflare_ruleset__rules__action_parameters__uri__query
type cloudflare_ruleset__rules__action_parameters__uri
type cloudflare_ruleset__rules__action_parameters
type cloudflare_ruleset__rules__exposed_credential_check
type cloudflare_ruleset__rules__logging
type cloudflare_ruleset__rules__ratelimit
type cloudflare_ruleset__rules
type cloudflare_ruleset

val cloudflare_ruleset :
  ?account_id:string ->
  ?description:string ->
  ?zone_id:string ->
  kind:string ->
  name:string ->
  phase:string ->
  rules:cloudflare_ruleset__rules list ->
  string ->
  unit
