(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

[@@@ocaml.warning "-33-27-26"]

open! Tf.Prelude

type cloudflare_ipsec_tunnel = {
  account_id : string option; [@option]
      (** The account identifier to target for the resource. **Modifying this attribute will force creation of a new resource.** *)
  allow_null_cipher : bool option; [@option]
      (** Specifies if this tunnel may use a null cipher (ENCR_NULL) in Phase 2. Defaults to `false`. *)
  cloudflare_endpoint : string;
      (** IP address assigned to the Cloudflare side of the IPsec tunnel. *)
  customer_endpoint : string;
      (** IP address assigned to the customer side of the IPsec tunnel. *)
  description : string option; [@option]
      (** An optional description of the IPsec tunnel. *)
  fqdn_id : string option; [@option]
      (** `remote_id` in the form of a fqdn. This value is generated by cloudflare. *)
  health_check_enabled : bool option; [@option]
      (** Specifies if ICMP tunnel health checks are enabled. Default: `true`. *)
  health_check_target : string option; [@option]
      (** The IP address of the customer endpoint that will receive tunnel health checks. Default: `<customer_gre_endpoint>`. *)
  health_check_type : string option; [@option]
      (** Specifies the ICMP echo type for the health check (`request` or `reply`). Available values: `request`, `reply` Default: `reply`. *)
  hex_id : string option; [@option]
      (** `remote_id` as a hex string. This value is generated by cloudflare. *)
  id : string option; [@option]  (** id *)
  interface_address : string;
      (** 31-bit prefix (/31 in CIDR notation) supporting 2 hosts, one for each side of the tunnel. *)
  name : string;  (** Name of the IPsec tunnel. *)
  psk : string option; [@option]
      (** Pre shared key to be used with the IPsec tunnel. If left unset, it will be autogenerated. *)
  remote_id : string option; [@option]
      (** ID to be used while setting up the IPsec tunnel. This value is generated by cloudflare. *)
  user_id : string option; [@option]
      (** `remote_id` in the form of an email address. This value is generated by cloudflare. *)
}
[@@deriving yojson_of]
(** Provides a resource, that manages IPsec tunnels for Magic Transit.
 *)

let cloudflare_ipsec_tunnel ?account_id ?allow_null_cipher
    ?description ?fqdn_id ?health_check_enabled ?health_check_target
    ?health_check_type ?hex_id ?id ?psk ?remote_id ?user_id
    ~cloudflare_endpoint ~customer_endpoint ~interface_address ~name
    __resource_id =
  let __resource_type = "cloudflare_ipsec_tunnel" in
  let __resource =
    {
      account_id;
      allow_null_cipher;
      cloudflare_endpoint;
      customer_endpoint;
      description;
      fqdn_id;
      health_check_enabled;
      health_check_target;
      health_check_type;
      hex_id;
      id;
      interface_address;
      name;
      psk;
      remote_id;
      user_id;
    }
  in
  Resource.add ~type_:__resource_type ~id:__resource_id
    (yojson_of_cloudflare_ipsec_tunnel __resource);
  ()
