(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_document_ai_warehouse_document_schema__property_definitions__date_time_type_options

type google_document_ai_warehouse_document_schema__property_definitions__enum_type_options

type google_document_ai_warehouse_document_schema__property_definitions__float_type_options

type google_document_ai_warehouse_document_schema__property_definitions__integer_type_options

type google_document_ai_warehouse_document_schema__property_definitions__map_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__date_time_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__enum_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__float_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__integer_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__map_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__schema_sources

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__text_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__timestamp_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options

type google_document_ai_warehouse_document_schema__property_definitions__schema_sources

type google_document_ai_warehouse_document_schema__property_definitions__text_type_options

type google_document_ai_warehouse_document_schema__property_definitions__timestamp_type_options

type google_document_ai_warehouse_document_schema__property_definitions

type google_document_ai_warehouse_document_schema__timeouts
type google_document_ai_warehouse_document_schema

type t = private {
  display_name : string prop;
  document_is_folder : bool prop;
  id : string prop;
  location : string prop;
  name : string prop;
  project_number : string prop;
}

val google_document_ai_warehouse_document_schema :
  ?document_is_folder:bool prop ->
  ?id:string prop ->
  ?timeouts:google_document_ai_warehouse_document_schema__timeouts ->
  display_name:string prop ->
  location:string prop ->
  project_number:string prop ->
  property_definitions:
    google_document_ai_warehouse_document_schema__property_definitions
    list ->
  string ->
  t
