(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_gke_hub_feature_membership__configmanagement__binauthz

type google_gke_hub_feature_membership__configmanagement__config_sync__git

type google_gke_hub_feature_membership__configmanagement__config_sync__oci

type google_gke_hub_feature_membership__configmanagement__config_sync

type google_gke_hub_feature_membership__configmanagement__hierarchy_controller

type google_gke_hub_feature_membership__configmanagement__policy_controller__monitoring

type google_gke_hub_feature_membership__configmanagement__policy_controller

type google_gke_hub_feature_membership__configmanagement
type google_gke_hub_feature_membership__mesh

type google_gke_hub_feature_membership__policycontroller__policy_controller_hub_config__deployment_configs__container_resources__limits

type google_gke_hub_feature_membership__policycontroller__policy_controller_hub_config__deployment_configs__container_resources__requests

type google_gke_hub_feature_membership__policycontroller__policy_controller_hub_config__deployment_configs__container_resources

type google_gke_hub_feature_membership__policycontroller__policy_controller_hub_config__deployment_configs__pod_tolerations

type google_gke_hub_feature_membership__policycontroller__policy_controller_hub_config__deployment_configs

type google_gke_hub_feature_membership__policycontroller__policy_controller_hub_config__monitoring

type google_gke_hub_feature_membership__policycontroller__policy_controller_hub_config__policy_content__bundles

type google_gke_hub_feature_membership__policycontroller__policy_controller_hub_config__policy_content__template_library

type google_gke_hub_feature_membership__policycontroller__policy_controller_hub_config__policy_content

type google_gke_hub_feature_membership__policycontroller__policy_controller_hub_config

type google_gke_hub_feature_membership__policycontroller
type google_gke_hub_feature_membership__timeouts
type google_gke_hub_feature_membership

type t = private {
  feature : string prop;
  id : string prop;
  location : string prop;
  membership : string prop;
  membership_location : string prop;
  project : string prop;
}

val google_gke_hub_feature_membership :
  ?id:string prop ->
  ?membership_location:string prop ->
  ?project:string prop ->
  ?timeouts:google_gke_hub_feature_membership__timeouts ->
  feature:string prop ->
  location:string prop ->
  membership:string prop ->
  configmanagement:
    google_gke_hub_feature_membership__configmanagement list ->
  mesh:google_gke_hub_feature_membership__mesh list ->
  policycontroller:
    google_gke_hub_feature_membership__policycontroller list ->
  string ->
  t
