(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf_core

(** PROVIDER SERIALIZATION *)

type batching

val batching :
  ?enable_batching:bool prop ->
  ?send_after:string prop ->
  unit ->
  batching

type google

val google :
  ?access_approval_custom_endpoint:string prop ->
  ?access_context_manager_custom_endpoint:string prop ->
  ?access_token:string prop ->
  ?active_directory_custom_endpoint:string prop ->
  ?add_terraform_attribution_label:bool prop ->
  ?alloydb_custom_endpoint:string prop ->
  ?apigee_custom_endpoint:string prop ->
  ?apikeys_custom_endpoint:string prop ->
  ?app_engine_custom_endpoint:string prop ->
  ?apphub_custom_endpoint:string prop ->
  ?artifact_registry_custom_endpoint:string prop ->
  ?assured_workloads_custom_endpoint:string prop ->
  ?beyondcorp_custom_endpoint:string prop ->
  ?big_query_custom_endpoint:string prop ->
  ?biglake_custom_endpoint:string prop ->
  ?bigquery_analytics_hub_custom_endpoint:string prop ->
  ?bigquery_connection_custom_endpoint:string prop ->
  ?bigquery_data_transfer_custom_endpoint:string prop ->
  ?bigquery_datapolicy_custom_endpoint:string prop ->
  ?bigquery_reservation_custom_endpoint:string prop ->
  ?bigtable_custom_endpoint:string prop ->
  ?billing_custom_endpoint:string prop ->
  ?billing_project:string prop ->
  ?binary_authorization_custom_endpoint:string prop ->
  ?blockchain_node_engine_custom_endpoint:string prop ->
  ?certificate_manager_custom_endpoint:string prop ->
  ?cloud_asset_custom_endpoint:string prop ->
  ?cloud_billing_custom_endpoint:string prop ->
  ?cloud_build_custom_endpoint:string prop ->
  ?cloud_build_worker_pool_custom_endpoint:string prop ->
  ?cloud_functions_custom_endpoint:string prop ->
  ?cloud_identity_custom_endpoint:string prop ->
  ?cloud_ids_custom_endpoint:string prop ->
  ?cloud_quotas_custom_endpoint:string prop ->
  ?cloud_resource_manager_custom_endpoint:string prop ->
  ?cloud_run_custom_endpoint:string prop ->
  ?cloud_run_v2_custom_endpoint:string prop ->
  ?cloud_scheduler_custom_endpoint:string prop ->
  ?cloud_tasks_custom_endpoint:string prop ->
  ?cloudbuildv2_custom_endpoint:string prop ->
  ?clouddeploy_custom_endpoint:string prop ->
  ?clouddomains_custom_endpoint:string prop ->
  ?cloudfunctions2_custom_endpoint:string prop ->
  ?composer_custom_endpoint:string prop ->
  ?compute_custom_endpoint:string prop ->
  ?container_analysis_custom_endpoint:string prop ->
  ?container_attached_custom_endpoint:string prop ->
  ?container_aws_custom_endpoint:string prop ->
  ?container_azure_custom_endpoint:string prop ->
  ?container_custom_endpoint:string prop ->
  ?core_billing_custom_endpoint:string prop ->
  ?credentials:string prop ->
  ?data_catalog_custom_endpoint:string prop ->
  ?data_fusion_custom_endpoint:string prop ->
  ?data_loss_prevention_custom_endpoint:string prop ->
  ?data_pipeline_custom_endpoint:string prop ->
  ?database_migration_service_custom_endpoint:string prop ->
  ?dataflow_custom_endpoint:string prop ->
  ?dataplex_custom_endpoint:string prop ->
  ?dataproc_custom_endpoint:string prop ->
  ?dataproc_metastore_custom_endpoint:string prop ->
  ?datastore_custom_endpoint:string prop ->
  ?datastream_custom_endpoint:string prop ->
  ?default_labels:(string * string prop) list ->
  ?deployment_manager_custom_endpoint:string prop ->
  ?dialogflow_custom_endpoint:string prop ->
  ?dialogflow_cx_custom_endpoint:string prop ->
  ?discovery_engine_custom_endpoint:string prop ->
  ?dns_custom_endpoint:string prop ->
  ?document_ai_custom_endpoint:string prop ->
  ?document_ai_warehouse_custom_endpoint:string prop ->
  ?edgecontainer_custom_endpoint:string prop ->
  ?edgenetwork_custom_endpoint:string prop ->
  ?essential_contacts_custom_endpoint:string prop ->
  ?eventarc_custom_endpoint:string prop ->
  ?filestore_custom_endpoint:string prop ->
  ?firebase_app_check_custom_endpoint:string prop ->
  ?firebaserules_custom_endpoint:string prop ->
  ?firestore_custom_endpoint:string prop ->
  ?gke_backup_custom_endpoint:string prop ->
  ?gke_hub2_custom_endpoint:string prop ->
  ?gke_hub_custom_endpoint:string prop ->
  ?gkehub_feature_custom_endpoint:string prop ->
  ?gkeonprem_custom_endpoint:string prop ->
  ?healthcare_custom_endpoint:string prop ->
  ?iam2_custom_endpoint:string prop ->
  ?iam_beta_custom_endpoint:string prop ->
  ?iam_credentials_custom_endpoint:string prop ->
  ?iam_custom_endpoint:string prop ->
  ?iam_workforce_pool_custom_endpoint:string prop ->
  ?iap_custom_endpoint:string prop ->
  ?identity_platform_custom_endpoint:string prop ->
  ?impersonate_service_account:string prop ->
  ?impersonate_service_account_delegates:string prop list ->
  ?integration_connectors_custom_endpoint:string prop ->
  ?integrations_custom_endpoint:string prop ->
  ?kms_custom_endpoint:string prop ->
  ?logging_custom_endpoint:string prop ->
  ?looker_custom_endpoint:string prop ->
  ?memcache_custom_endpoint:string prop ->
  ?migration_center_custom_endpoint:string prop ->
  ?ml_engine_custom_endpoint:string prop ->
  ?monitoring_custom_endpoint:string prop ->
  ?netapp_custom_endpoint:string prop ->
  ?network_connectivity_custom_endpoint:string prop ->
  ?network_management_custom_endpoint:string prop ->
  ?network_security_custom_endpoint:string prop ->
  ?network_services_custom_endpoint:string prop ->
  ?notebooks_custom_endpoint:string prop ->
  ?org_policy_custom_endpoint:string prop ->
  ?os_config_custom_endpoint:string prop ->
  ?os_login_custom_endpoint:string prop ->
  ?privateca_custom_endpoint:string prop ->
  ?privileged_access_manager_custom_endpoint:string prop ->
  ?project:string prop ->
  ?public_ca_custom_endpoint:string prop ->
  ?pubsub_custom_endpoint:string prop ->
  ?pubsub_lite_custom_endpoint:string prop ->
  ?recaptcha_enterprise_custom_endpoint:string prop ->
  ?redis_custom_endpoint:string prop ->
  ?region:string prop ->
  ?request_reason:string prop ->
  ?request_timeout:string prop ->
  ?resource_manager_custom_endpoint:string prop ->
  ?resource_manager_v3_custom_endpoint:string prop ->
  ?scopes:string prop list ->
  ?secret_manager_custom_endpoint:string prop ->
  ?secure_source_manager_custom_endpoint:string prop ->
  ?security_center_custom_endpoint:string prop ->
  ?security_center_management_custom_endpoint:string prop ->
  ?security_center_v2_custom_endpoint:string prop ->
  ?securityposture_custom_endpoint:string prop ->
  ?service_management_custom_endpoint:string prop ->
  ?service_networking_custom_endpoint:string prop ->
  ?service_usage_custom_endpoint:string prop ->
  ?site_verification_custom_endpoint:string prop ->
  ?source_repo_custom_endpoint:string prop ->
  ?spanner_custom_endpoint:string prop ->
  ?sql_custom_endpoint:string prop ->
  ?storage_custom_endpoint:string prop ->
  ?storage_insights_custom_endpoint:string prop ->
  ?storage_transfer_custom_endpoint:string prop ->
  ?tags_custom_endpoint:string prop ->
  ?tags_location_custom_endpoint:string prop ->
  ?terraform_attribution_label_addition_strategy:string prop ->
  ?tpu_custom_endpoint:string prop ->
  ?universe_domain:string prop ->
  ?user_project_override:bool prop ->
  ?vertex_ai_custom_endpoint:string prop ->
  ?vmwareengine_custom_endpoint:string prop ->
  ?vpc_access_custom_endpoint:string prop ->
  ?workbench_custom_endpoint:string prop ->
  ?workflows_custom_endpoint:string prop ->
  ?zone:string prop ->
  ?batching:batching list ->
  unit ->
  google

val yojson_of_google : google -> json

(** PROVIDER REGISTRATION *)

val register :
  ?tf_module:tf_module ->
  ?access_approval_custom_endpoint:string prop ->
  ?access_context_manager_custom_endpoint:string prop ->
  ?access_token:string prop ->
  ?active_directory_custom_endpoint:string prop ->
  ?add_terraform_attribution_label:bool prop ->
  ?alloydb_custom_endpoint:string prop ->
  ?apigee_custom_endpoint:string prop ->
  ?apikeys_custom_endpoint:string prop ->
  ?app_engine_custom_endpoint:string prop ->
  ?apphub_custom_endpoint:string prop ->
  ?artifact_registry_custom_endpoint:string prop ->
  ?assured_workloads_custom_endpoint:string prop ->
  ?beyondcorp_custom_endpoint:string prop ->
  ?big_query_custom_endpoint:string prop ->
  ?biglake_custom_endpoint:string prop ->
  ?bigquery_analytics_hub_custom_endpoint:string prop ->
  ?bigquery_connection_custom_endpoint:string prop ->
  ?bigquery_data_transfer_custom_endpoint:string prop ->
  ?bigquery_datapolicy_custom_endpoint:string prop ->
  ?bigquery_reservation_custom_endpoint:string prop ->
  ?bigtable_custom_endpoint:string prop ->
  ?billing_custom_endpoint:string prop ->
  ?billing_project:string prop ->
  ?binary_authorization_custom_endpoint:string prop ->
  ?blockchain_node_engine_custom_endpoint:string prop ->
  ?certificate_manager_custom_endpoint:string prop ->
  ?cloud_asset_custom_endpoint:string prop ->
  ?cloud_billing_custom_endpoint:string prop ->
  ?cloud_build_custom_endpoint:string prop ->
  ?cloud_build_worker_pool_custom_endpoint:string prop ->
  ?cloud_functions_custom_endpoint:string prop ->
  ?cloud_identity_custom_endpoint:string prop ->
  ?cloud_ids_custom_endpoint:string prop ->
  ?cloud_quotas_custom_endpoint:string prop ->
  ?cloud_resource_manager_custom_endpoint:string prop ->
  ?cloud_run_custom_endpoint:string prop ->
  ?cloud_run_v2_custom_endpoint:string prop ->
  ?cloud_scheduler_custom_endpoint:string prop ->
  ?cloud_tasks_custom_endpoint:string prop ->
  ?cloudbuildv2_custom_endpoint:string prop ->
  ?clouddeploy_custom_endpoint:string prop ->
  ?clouddomains_custom_endpoint:string prop ->
  ?cloudfunctions2_custom_endpoint:string prop ->
  ?composer_custom_endpoint:string prop ->
  ?compute_custom_endpoint:string prop ->
  ?container_analysis_custom_endpoint:string prop ->
  ?container_attached_custom_endpoint:string prop ->
  ?container_aws_custom_endpoint:string prop ->
  ?container_azure_custom_endpoint:string prop ->
  ?container_custom_endpoint:string prop ->
  ?core_billing_custom_endpoint:string prop ->
  ?credentials:string prop ->
  ?data_catalog_custom_endpoint:string prop ->
  ?data_fusion_custom_endpoint:string prop ->
  ?data_loss_prevention_custom_endpoint:string prop ->
  ?data_pipeline_custom_endpoint:string prop ->
  ?database_migration_service_custom_endpoint:string prop ->
  ?dataflow_custom_endpoint:string prop ->
  ?dataplex_custom_endpoint:string prop ->
  ?dataproc_custom_endpoint:string prop ->
  ?dataproc_metastore_custom_endpoint:string prop ->
  ?datastore_custom_endpoint:string prop ->
  ?datastream_custom_endpoint:string prop ->
  ?default_labels:(string * string prop) list ->
  ?deployment_manager_custom_endpoint:string prop ->
  ?dialogflow_custom_endpoint:string prop ->
  ?dialogflow_cx_custom_endpoint:string prop ->
  ?discovery_engine_custom_endpoint:string prop ->
  ?dns_custom_endpoint:string prop ->
  ?document_ai_custom_endpoint:string prop ->
  ?document_ai_warehouse_custom_endpoint:string prop ->
  ?edgecontainer_custom_endpoint:string prop ->
  ?edgenetwork_custom_endpoint:string prop ->
  ?essential_contacts_custom_endpoint:string prop ->
  ?eventarc_custom_endpoint:string prop ->
  ?filestore_custom_endpoint:string prop ->
  ?firebase_app_check_custom_endpoint:string prop ->
  ?firebaserules_custom_endpoint:string prop ->
  ?firestore_custom_endpoint:string prop ->
  ?gke_backup_custom_endpoint:string prop ->
  ?gke_hub2_custom_endpoint:string prop ->
  ?gke_hub_custom_endpoint:string prop ->
  ?gkehub_feature_custom_endpoint:string prop ->
  ?gkeonprem_custom_endpoint:string prop ->
  ?healthcare_custom_endpoint:string prop ->
  ?iam2_custom_endpoint:string prop ->
  ?iam_beta_custom_endpoint:string prop ->
  ?iam_credentials_custom_endpoint:string prop ->
  ?iam_custom_endpoint:string prop ->
  ?iam_workforce_pool_custom_endpoint:string prop ->
  ?iap_custom_endpoint:string prop ->
  ?identity_platform_custom_endpoint:string prop ->
  ?impersonate_service_account:string prop ->
  ?impersonate_service_account_delegates:string prop list ->
  ?integration_connectors_custom_endpoint:string prop ->
  ?integrations_custom_endpoint:string prop ->
  ?kms_custom_endpoint:string prop ->
  ?logging_custom_endpoint:string prop ->
  ?looker_custom_endpoint:string prop ->
  ?memcache_custom_endpoint:string prop ->
  ?migration_center_custom_endpoint:string prop ->
  ?ml_engine_custom_endpoint:string prop ->
  ?monitoring_custom_endpoint:string prop ->
  ?netapp_custom_endpoint:string prop ->
  ?network_connectivity_custom_endpoint:string prop ->
  ?network_management_custom_endpoint:string prop ->
  ?network_security_custom_endpoint:string prop ->
  ?network_services_custom_endpoint:string prop ->
  ?notebooks_custom_endpoint:string prop ->
  ?org_policy_custom_endpoint:string prop ->
  ?os_config_custom_endpoint:string prop ->
  ?os_login_custom_endpoint:string prop ->
  ?privateca_custom_endpoint:string prop ->
  ?privileged_access_manager_custom_endpoint:string prop ->
  ?project:string prop ->
  ?public_ca_custom_endpoint:string prop ->
  ?pubsub_custom_endpoint:string prop ->
  ?pubsub_lite_custom_endpoint:string prop ->
  ?recaptcha_enterprise_custom_endpoint:string prop ->
  ?redis_custom_endpoint:string prop ->
  ?region:string prop ->
  ?request_reason:string prop ->
  ?request_timeout:string prop ->
  ?resource_manager_custom_endpoint:string prop ->
  ?resource_manager_v3_custom_endpoint:string prop ->
  ?scopes:string prop list ->
  ?secret_manager_custom_endpoint:string prop ->
  ?secure_source_manager_custom_endpoint:string prop ->
  ?security_center_custom_endpoint:string prop ->
  ?security_center_management_custom_endpoint:string prop ->
  ?security_center_v2_custom_endpoint:string prop ->
  ?securityposture_custom_endpoint:string prop ->
  ?service_management_custom_endpoint:string prop ->
  ?service_networking_custom_endpoint:string prop ->
  ?service_usage_custom_endpoint:string prop ->
  ?site_verification_custom_endpoint:string prop ->
  ?source_repo_custom_endpoint:string prop ->
  ?spanner_custom_endpoint:string prop ->
  ?sql_custom_endpoint:string prop ->
  ?storage_custom_endpoint:string prop ->
  ?storage_insights_custom_endpoint:string prop ->
  ?storage_transfer_custom_endpoint:string prop ->
  ?tags_custom_endpoint:string prop ->
  ?tags_location_custom_endpoint:string prop ->
  ?terraform_attribution_label_addition_strategy:string prop ->
  ?tpu_custom_endpoint:string prop ->
  ?universe_domain:string prop ->
  ?user_project_override:bool prop ->
  ?vertex_ai_custom_endpoint:string prop ->
  ?vmwareengine_custom_endpoint:string prop ->
  ?vpc_access_custom_endpoint:string prop ->
  ?workbench_custom_endpoint:string prop ->
  ?workflows_custom_endpoint:string prop ->
  ?zone:string prop ->
  ?batching:batching list ->
  version:string ->
  unit ->
  unit

val make :
  ?access_approval_custom_endpoint:string prop ->
  ?access_context_manager_custom_endpoint:string prop ->
  ?access_token:string prop ->
  ?active_directory_custom_endpoint:string prop ->
  ?add_terraform_attribution_label:bool prop ->
  ?alloydb_custom_endpoint:string prop ->
  ?apigee_custom_endpoint:string prop ->
  ?apikeys_custom_endpoint:string prop ->
  ?app_engine_custom_endpoint:string prop ->
  ?apphub_custom_endpoint:string prop ->
  ?artifact_registry_custom_endpoint:string prop ->
  ?assured_workloads_custom_endpoint:string prop ->
  ?beyondcorp_custom_endpoint:string prop ->
  ?big_query_custom_endpoint:string prop ->
  ?biglake_custom_endpoint:string prop ->
  ?bigquery_analytics_hub_custom_endpoint:string prop ->
  ?bigquery_connection_custom_endpoint:string prop ->
  ?bigquery_data_transfer_custom_endpoint:string prop ->
  ?bigquery_datapolicy_custom_endpoint:string prop ->
  ?bigquery_reservation_custom_endpoint:string prop ->
  ?bigtable_custom_endpoint:string prop ->
  ?billing_custom_endpoint:string prop ->
  ?billing_project:string prop ->
  ?binary_authorization_custom_endpoint:string prop ->
  ?blockchain_node_engine_custom_endpoint:string prop ->
  ?certificate_manager_custom_endpoint:string prop ->
  ?cloud_asset_custom_endpoint:string prop ->
  ?cloud_billing_custom_endpoint:string prop ->
  ?cloud_build_custom_endpoint:string prop ->
  ?cloud_build_worker_pool_custom_endpoint:string prop ->
  ?cloud_functions_custom_endpoint:string prop ->
  ?cloud_identity_custom_endpoint:string prop ->
  ?cloud_ids_custom_endpoint:string prop ->
  ?cloud_quotas_custom_endpoint:string prop ->
  ?cloud_resource_manager_custom_endpoint:string prop ->
  ?cloud_run_custom_endpoint:string prop ->
  ?cloud_run_v2_custom_endpoint:string prop ->
  ?cloud_scheduler_custom_endpoint:string prop ->
  ?cloud_tasks_custom_endpoint:string prop ->
  ?cloudbuildv2_custom_endpoint:string prop ->
  ?clouddeploy_custom_endpoint:string prop ->
  ?clouddomains_custom_endpoint:string prop ->
  ?cloudfunctions2_custom_endpoint:string prop ->
  ?composer_custom_endpoint:string prop ->
  ?compute_custom_endpoint:string prop ->
  ?container_analysis_custom_endpoint:string prop ->
  ?container_attached_custom_endpoint:string prop ->
  ?container_aws_custom_endpoint:string prop ->
  ?container_azure_custom_endpoint:string prop ->
  ?container_custom_endpoint:string prop ->
  ?core_billing_custom_endpoint:string prop ->
  ?credentials:string prop ->
  ?data_catalog_custom_endpoint:string prop ->
  ?data_fusion_custom_endpoint:string prop ->
  ?data_loss_prevention_custom_endpoint:string prop ->
  ?data_pipeline_custom_endpoint:string prop ->
  ?database_migration_service_custom_endpoint:string prop ->
  ?dataflow_custom_endpoint:string prop ->
  ?dataplex_custom_endpoint:string prop ->
  ?dataproc_custom_endpoint:string prop ->
  ?dataproc_metastore_custom_endpoint:string prop ->
  ?datastore_custom_endpoint:string prop ->
  ?datastream_custom_endpoint:string prop ->
  ?default_labels:(string * string prop) list ->
  ?deployment_manager_custom_endpoint:string prop ->
  ?dialogflow_custom_endpoint:string prop ->
  ?dialogflow_cx_custom_endpoint:string prop ->
  ?discovery_engine_custom_endpoint:string prop ->
  ?dns_custom_endpoint:string prop ->
  ?document_ai_custom_endpoint:string prop ->
  ?document_ai_warehouse_custom_endpoint:string prop ->
  ?edgecontainer_custom_endpoint:string prop ->
  ?edgenetwork_custom_endpoint:string prop ->
  ?essential_contacts_custom_endpoint:string prop ->
  ?eventarc_custom_endpoint:string prop ->
  ?filestore_custom_endpoint:string prop ->
  ?firebase_app_check_custom_endpoint:string prop ->
  ?firebaserules_custom_endpoint:string prop ->
  ?firestore_custom_endpoint:string prop ->
  ?gke_backup_custom_endpoint:string prop ->
  ?gke_hub2_custom_endpoint:string prop ->
  ?gke_hub_custom_endpoint:string prop ->
  ?gkehub_feature_custom_endpoint:string prop ->
  ?gkeonprem_custom_endpoint:string prop ->
  ?healthcare_custom_endpoint:string prop ->
  ?iam2_custom_endpoint:string prop ->
  ?iam_beta_custom_endpoint:string prop ->
  ?iam_credentials_custom_endpoint:string prop ->
  ?iam_custom_endpoint:string prop ->
  ?iam_workforce_pool_custom_endpoint:string prop ->
  ?iap_custom_endpoint:string prop ->
  ?identity_platform_custom_endpoint:string prop ->
  ?impersonate_service_account:string prop ->
  ?impersonate_service_account_delegates:string prop list ->
  ?integration_connectors_custom_endpoint:string prop ->
  ?integrations_custom_endpoint:string prop ->
  ?kms_custom_endpoint:string prop ->
  ?logging_custom_endpoint:string prop ->
  ?looker_custom_endpoint:string prop ->
  ?memcache_custom_endpoint:string prop ->
  ?migration_center_custom_endpoint:string prop ->
  ?ml_engine_custom_endpoint:string prop ->
  ?monitoring_custom_endpoint:string prop ->
  ?netapp_custom_endpoint:string prop ->
  ?network_connectivity_custom_endpoint:string prop ->
  ?network_management_custom_endpoint:string prop ->
  ?network_security_custom_endpoint:string prop ->
  ?network_services_custom_endpoint:string prop ->
  ?notebooks_custom_endpoint:string prop ->
  ?org_policy_custom_endpoint:string prop ->
  ?os_config_custom_endpoint:string prop ->
  ?os_login_custom_endpoint:string prop ->
  ?privateca_custom_endpoint:string prop ->
  ?privileged_access_manager_custom_endpoint:string prop ->
  ?project:string prop ->
  ?public_ca_custom_endpoint:string prop ->
  ?pubsub_custom_endpoint:string prop ->
  ?pubsub_lite_custom_endpoint:string prop ->
  ?recaptcha_enterprise_custom_endpoint:string prop ->
  ?redis_custom_endpoint:string prop ->
  ?region:string prop ->
  ?request_reason:string prop ->
  ?request_timeout:string prop ->
  ?resource_manager_custom_endpoint:string prop ->
  ?resource_manager_v3_custom_endpoint:string prop ->
  ?scopes:string prop list ->
  ?secret_manager_custom_endpoint:string prop ->
  ?secure_source_manager_custom_endpoint:string prop ->
  ?security_center_custom_endpoint:string prop ->
  ?security_center_management_custom_endpoint:string prop ->
  ?security_center_v2_custom_endpoint:string prop ->
  ?securityposture_custom_endpoint:string prop ->
  ?service_management_custom_endpoint:string prop ->
  ?service_networking_custom_endpoint:string prop ->
  ?service_usage_custom_endpoint:string prop ->
  ?site_verification_custom_endpoint:string prop ->
  ?source_repo_custom_endpoint:string prop ->
  ?spanner_custom_endpoint:string prop ->
  ?sql_custom_endpoint:string prop ->
  ?storage_custom_endpoint:string prop ->
  ?storage_insights_custom_endpoint:string prop ->
  ?storage_transfer_custom_endpoint:string prop ->
  ?tags_custom_endpoint:string prop ->
  ?tags_location_custom_endpoint:string prop ->
  ?terraform_attribution_label_addition_strategy:string prop ->
  ?tpu_custom_endpoint:string prop ->
  ?universe_domain:string prop ->
  ?user_project_override:bool prop ->
  ?vertex_ai_custom_endpoint:string prop ->
  ?vmwareengine_custom_endpoint:string prop ->
  ?vpc_access_custom_endpoint:string prop ->
  ?workbench_custom_endpoint:string prop ->
  ?workflows_custom_endpoint:string prop ->
  ?zone:string prop ->
  ?batching:batching list ->
  unit ->
  Tf_core.provider
