(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_appmesh_route__spec__grpc_route__action__weighted_target
type aws_appmesh_route__spec__grpc_route__action

type aws_appmesh_route__spec__grpc_route__match__metadata__match__range

type aws_appmesh_route__spec__grpc_route__match__metadata__match
type aws_appmesh_route__spec__grpc_route__match__metadata
type aws_appmesh_route__spec__grpc_route__match

type aws_appmesh_route__spec__grpc_route__retry_policy__per_retry_timeout

type aws_appmesh_route__spec__grpc_route__retry_policy
type aws_appmesh_route__spec__grpc_route__timeout__idle
type aws_appmesh_route__spec__grpc_route__timeout__per_request
type aws_appmesh_route__spec__grpc_route__timeout
type aws_appmesh_route__spec__grpc_route
type aws_appmesh_route__spec__http2_route__action__weighted_target
type aws_appmesh_route__spec__http2_route__action
type aws_appmesh_route__spec__http2_route__match__header__match__range
type aws_appmesh_route__spec__http2_route__match__header__match
type aws_appmesh_route__spec__http2_route__match__header
type aws_appmesh_route__spec__http2_route__match__path

type aws_appmesh_route__spec__http2_route__match__query_parameter__match

type aws_appmesh_route__spec__http2_route__match__query_parameter
type aws_appmesh_route__spec__http2_route__match

type aws_appmesh_route__spec__http2_route__retry_policy__per_retry_timeout

type aws_appmesh_route__spec__http2_route__retry_policy
type aws_appmesh_route__spec__http2_route__timeout__idle
type aws_appmesh_route__spec__http2_route__timeout__per_request
type aws_appmesh_route__spec__http2_route__timeout
type aws_appmesh_route__spec__http2_route
type aws_appmesh_route__spec__http_route__action__weighted_target
type aws_appmesh_route__spec__http_route__action
type aws_appmesh_route__spec__http_route__match__header__match__range
type aws_appmesh_route__spec__http_route__match__header__match
type aws_appmesh_route__spec__http_route__match__header
type aws_appmesh_route__spec__http_route__match__path

type aws_appmesh_route__spec__http_route__match__query_parameter__match

type aws_appmesh_route__spec__http_route__match__query_parameter
type aws_appmesh_route__spec__http_route__match

type aws_appmesh_route__spec__http_route__retry_policy__per_retry_timeout

type aws_appmesh_route__spec__http_route__retry_policy
type aws_appmesh_route__spec__http_route__timeout__idle
type aws_appmesh_route__spec__http_route__timeout__per_request
type aws_appmesh_route__spec__http_route__timeout
type aws_appmesh_route__spec__http_route
type aws_appmesh_route__spec__tcp_route__action__weighted_target
type aws_appmesh_route__spec__tcp_route__action
type aws_appmesh_route__spec__tcp_route__match
type aws_appmesh_route__spec__tcp_route__timeout__idle
type aws_appmesh_route__spec__tcp_route__timeout
type aws_appmesh_route__spec__tcp_route
type aws_appmesh_route__spec
type aws_appmesh_route

val aws_appmesh_route :
  ?id:string ->
  ?mesh_owner:string ->
  ?tags:(string * string) list ->
  ?tags_all:(string * string) list ->
  mesh_name:string ->
  name:string ->
  virtual_router_name:string ->
  spec:aws_appmesh_route__spec list ->
  string ->
  unit
