(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__amplitude

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__custom_connector__api_key

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__custom_connector__basic

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__custom_connector__custom

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__custom_connector__oauth2__oauth_request

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__custom_connector__oauth2

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__custom_connector

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__datadog

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__dynatrace

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__google_analytics__oauth_request

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__google_analytics

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__honeycode__oauth_request

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__honeycode

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__infor_nexus

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__marketo__oauth_request

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__marketo

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__redshift

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__salesforce__oauth_request

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__salesforce

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__sapo_data__basic_auth_credentials

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__sapo_data__oauth_credentials__oauth_request

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__sapo_data__oauth_credentials

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__sapo_data

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__service_now

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__singular

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__slack__oauth_request

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__slack

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__snowflake

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__trendmicro

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__veeva

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__zendesk__oauth_request

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials__zendesk

type aws_appflow_connector_profile__connector_profile_config__connector_profile_credentials

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__amplitude

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__custom_connector__oauth2_properties

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__custom_connector

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__datadog

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__dynatrace

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__google_analytics

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__honeycode

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__infor_nexus

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__marketo

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__redshift

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__salesforce

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__sapo_data__oauth_properties

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__sapo_data

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__service_now

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__singular

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__slack

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__snowflake

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__trendmicro

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__veeva

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties__zendesk

type aws_appflow_connector_profile__connector_profile_config__connector_profile_properties

type aws_appflow_connector_profile__connector_profile_config
type aws_appflow_connector_profile

val aws_appflow_connector_profile :
  ?connector_label:string ->
  connection_mode:string ->
  connector_type:string ->
  name:string ->
  connector_profile_config:
    aws_appflow_connector_profile__connector_profile_config list ->
  string ->
  unit
