(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_appflow_flow__destination_flow_config__destination_connector_properties__custom_connector__error_handling_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__custom_connector

type aws_appflow_flow__destination_flow_config__destination_connector_properties__customer_profiles

type aws_appflow_flow__destination_flow_config__destination_connector_properties__event_bridge__error_handling_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__event_bridge

type aws_appflow_flow__destination_flow_config__destination_connector_properties__honeycode__error_handling_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__honeycode

type aws_appflow_flow__destination_flow_config__destination_connector_properties__lookout_metrics

type aws_appflow_flow__destination_flow_config__destination_connector_properties__marketo__error_handling_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__marketo

type aws_appflow_flow__destination_flow_config__destination_connector_properties__redshift__error_handling_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__redshift

type aws_appflow_flow__destination_flow_config__destination_connector_properties__s3__s3_output_format_config__aggregation_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__s3__s3_output_format_config__prefix_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__s3__s3_output_format_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__s3

type aws_appflow_flow__destination_flow_config__destination_connector_properties__salesforce__error_handling_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__salesforce

type aws_appflow_flow__destination_flow_config__destination_connector_properties__sapo_data__error_handling_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__sapo_data__success_response_handling_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__sapo_data

type aws_appflow_flow__destination_flow_config__destination_connector_properties__snowflake__error_handling_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__snowflake

type aws_appflow_flow__destination_flow_config__destination_connector_properties__upsolver__s3_output_format_config__aggregation_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__upsolver__s3_output_format_config__prefix_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__upsolver__s3_output_format_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__upsolver

type aws_appflow_flow__destination_flow_config__destination_connector_properties__zendesk__error_handling_config

type aws_appflow_flow__destination_flow_config__destination_connector_properties__zendesk

type aws_appflow_flow__destination_flow_config__destination_connector_properties

type aws_appflow_flow__destination_flow_config
type aws_appflow_flow__source_flow_config__incremental_pull_config

type aws_appflow_flow__source_flow_config__source_connector_properties__amplitude

type aws_appflow_flow__source_flow_config__source_connector_properties__custom_connector

type aws_appflow_flow__source_flow_config__source_connector_properties__datadog

type aws_appflow_flow__source_flow_config__source_connector_properties__dynatrace

type aws_appflow_flow__source_flow_config__source_connector_properties__google_analytics

type aws_appflow_flow__source_flow_config__source_connector_properties__infor_nexus

type aws_appflow_flow__source_flow_config__source_connector_properties__marketo

type aws_appflow_flow__source_flow_config__source_connector_properties__s3__s3_input_format_config

type aws_appflow_flow__source_flow_config__source_connector_properties__s3

type aws_appflow_flow__source_flow_config__source_connector_properties__salesforce

type aws_appflow_flow__source_flow_config__source_connector_properties__sapo_data

type aws_appflow_flow__source_flow_config__source_connector_properties__service_now

type aws_appflow_flow__source_flow_config__source_connector_properties__singular

type aws_appflow_flow__source_flow_config__source_connector_properties__slack

type aws_appflow_flow__source_flow_config__source_connector_properties__trendmicro

type aws_appflow_flow__source_flow_config__source_connector_properties__veeva

type aws_appflow_flow__source_flow_config__source_connector_properties__zendesk

type aws_appflow_flow__source_flow_config__source_connector_properties
type aws_appflow_flow__source_flow_config
type aws_appflow_flow__task__connector_operator
type aws_appflow_flow__task
type aws_appflow_flow__trigger_config__trigger_properties__scheduled
type aws_appflow_flow__trigger_config__trigger_properties
type aws_appflow_flow__trigger_config
type aws_appflow_flow

val aws_appflow_flow :
  ?description:string prop ->
  ?id:string prop ->
  ?kms_arn:string prop ->
  ?tags:(string * string prop) list ->
  ?tags_all:(string * string prop) list ->
  name:string prop ->
  destination_flow_config:
    aws_appflow_flow__destination_flow_config list ->
  source_flow_config:aws_appflow_flow__source_flow_config list ->
  task:aws_appflow_flow__task list ->
  trigger_config:aws_appflow_flow__trigger_config list ->
  string ->
  unit
