(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_appmesh_route__spec__grpc_route__action__weighted_target
type aws_appmesh_route__spec__grpc_route__action

type aws_appmesh_route__spec__grpc_route__match__metadata__match__range

type aws_appmesh_route__spec__grpc_route__match__metadata__match
type aws_appmesh_route__spec__grpc_route__match__metadata
type aws_appmesh_route__spec__grpc_route__match

type aws_appmesh_route__spec__grpc_route__retry_policy__per_retry_timeout

type aws_appmesh_route__spec__grpc_route__retry_policy
type aws_appmesh_route__spec__grpc_route__timeout__idle
type aws_appmesh_route__spec__grpc_route__timeout__per_request
type aws_appmesh_route__spec__grpc_route__timeout
type aws_appmesh_route__spec__grpc_route
type aws_appmesh_route__spec__http2_route__action__weighted_target
type aws_appmesh_route__spec__http2_route__action
type aws_appmesh_route__spec__http2_route__match__header__match__range
type aws_appmesh_route__spec__http2_route__match__header__match
type aws_appmesh_route__spec__http2_route__match__header
type aws_appmesh_route__spec__http2_route__match__path

type aws_appmesh_route__spec__http2_route__match__query_parameter__match

type aws_appmesh_route__spec__http2_route__match__query_parameter
type aws_appmesh_route__spec__http2_route__match

type aws_appmesh_route__spec__http2_route__retry_policy__per_retry_timeout

type aws_appmesh_route__spec__http2_route__retry_policy
type aws_appmesh_route__spec__http2_route__timeout__idle
type aws_appmesh_route__spec__http2_route__timeout__per_request
type aws_appmesh_route__spec__http2_route__timeout
type aws_appmesh_route__spec__http2_route
type aws_appmesh_route__spec__http_route__action__weighted_target
type aws_appmesh_route__spec__http_route__action
type aws_appmesh_route__spec__http_route__match__header__match__range
type aws_appmesh_route__spec__http_route__match__header__match
type aws_appmesh_route__spec__http_route__match__header
type aws_appmesh_route__spec__http_route__match__path

type aws_appmesh_route__spec__http_route__match__query_parameter__match

type aws_appmesh_route__spec__http_route__match__query_parameter
type aws_appmesh_route__spec__http_route__match

type aws_appmesh_route__spec__http_route__retry_policy__per_retry_timeout

type aws_appmesh_route__spec__http_route__retry_policy
type aws_appmesh_route__spec__http_route__timeout__idle
type aws_appmesh_route__spec__http_route__timeout__per_request
type aws_appmesh_route__spec__http_route__timeout
type aws_appmesh_route__spec__http_route
type aws_appmesh_route__spec__tcp_route__action__weighted_target
type aws_appmesh_route__spec__tcp_route__action
type aws_appmesh_route__spec__tcp_route__match
type aws_appmesh_route__spec__tcp_route__timeout__idle
type aws_appmesh_route__spec__tcp_route__timeout
type aws_appmesh_route__spec__tcp_route
type aws_appmesh_route__spec
type aws_appmesh_route

type t = private {
  arn : string prop;
  created_date : string prop;
  id : string prop;
  last_updated_date : string prop;
  mesh_name : string prop;
  mesh_owner : string prop;
  name : string prop;
  resource_owner : string prop;
  tags : (string * string) list prop;
  tags_all : (string * string) list prop;
  virtual_router_name : string prop;
}

val aws_appmesh_route :
  ?id:string prop ->
  ?mesh_owner:string prop ->
  ?tags:(string * string prop) list ->
  ?tags_all:(string * string prop) list ->
  mesh_name:string prop ->
  name:string prop ->
  virtual_router_name:string prop ->
  spec:aws_appmesh_route__spec list ->
  string ->
  t
