(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_cloudfront_field_level_encryption_config__content_type_profile_config__content_type_profiles__items

type aws_cloudfront_field_level_encryption_config__content_type_profile_config__content_type_profiles

type aws_cloudfront_field_level_encryption_config__content_type_profile_config

type aws_cloudfront_field_level_encryption_config__query_arg_profile_config__query_arg_profiles__items

type aws_cloudfront_field_level_encryption_config__query_arg_profile_config__query_arg_profiles

type aws_cloudfront_field_level_encryption_config__query_arg_profile_config

type aws_cloudfront_field_level_encryption_config

val aws_cloudfront_field_level_encryption_config :
  ?comment:string ->
  content_type_profile_config:
    aws_cloudfront_field_level_encryption_config__content_type_profile_config
    list ->
  query_arg_profile_config:
    aws_cloudfront_field_level_encryption_config__query_arg_profile_config
    list ->
  string ->
  unit
