(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_lexv2models_slot__multiple_values_setting
type aws_lexv2models_slot__obfuscation_setting
type aws_lexv2models_slot__timeouts

type aws_lexv2models_slot__value_elicitation_setting__default_value_specification__default_value_list

type aws_lexv2models_slot__value_elicitation_setting__default_value_specification

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__message__custom_playload

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__message__image_response_card__button

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__message__image_response_card

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__message__plain_text_message

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__message__ssml_message

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__message

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__variation__custom_playload

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__variation__image_response_card__button

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__variation__image_response_card

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__variation__plain_text_message

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__variation__ssml_message

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group__variation

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__message_group

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__prompt_attempts_specification__allowed_input_types

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification__audio_specification

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification__dtmf_specification

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__prompt_attempts_specification__text_input_specification

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification__prompt_attempts_specification

type aws_lexv2models_slot__value_elicitation_setting__prompt_specification

type aws_lexv2models_slot__value_elicitation_setting__sample_utterance

type aws_lexv2models_slot__value_elicitation_setting__slot_resolution_setting

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__custom_playload

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__image_response_card__button

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__image_response_card

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__plain_text_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__ssml_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__custom_playload

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__image_response_card__button

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__image_response_card

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__plain_text_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__ssml_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response__message_group

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__continue_response

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__custom_playload

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__image_response_card__button

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__image_response_card

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__plain_text_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__ssml_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__custom_playload

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__image_response_card__button

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__image_response_card

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__plain_text_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__ssml_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__still_waiting_response

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__custom_playload

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__image_response_card__button

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__image_response_card

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__plain_text_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__ssml_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__custom_playload

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__image_response_card__button

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__image_response_card

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__plain_text_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__ssml_message

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification__waiting_response

type aws_lexv2models_slot__value_elicitation_setting__wait_and_continue_specification

type aws_lexv2models_slot__value_elicitation_setting
type aws_lexv2models_slot

val aws_lexv2models_slot :
  ?description:string ->
  ?slot_type_id:string ->
  ?timeouts:aws_lexv2models_slot__timeouts ->
  bot_id:string ->
  bot_version:string ->
  intent_id:string ->
  locale_id:string ->
  name:string ->
  multiple_values_setting:
    aws_lexv2models_slot__multiple_values_setting list ->
  obfuscation_setting:aws_lexv2models_slot__obfuscation_setting list ->
  value_elicitation_setting:
    aws_lexv2models_slot__value_elicitation_setting list ->
  string ->
  unit
