(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_kinesisanalyticsv2_application__application_configuration__application_code_configuration__code_content__s3_content_location

type aws_kinesisanalyticsv2_application__application_configuration__application_code_configuration__code_content

type aws_kinesisanalyticsv2_application__application_configuration__application_code_configuration

type aws_kinesisanalyticsv2_application__application_configuration__application_snapshot_configuration

type aws_kinesisanalyticsv2_application__application_configuration__environment_properties__property_group

type aws_kinesisanalyticsv2_application__application_configuration__environment_properties

type aws_kinesisanalyticsv2_application__application_configuration__flink_application_configuration__checkpoint_configuration

type aws_kinesisanalyticsv2_application__application_configuration__flink_application_configuration__monitoring_configuration

type aws_kinesisanalyticsv2_application__application_configuration__flink_application_configuration__parallelism_configuration

type aws_kinesisanalyticsv2_application__application_configuration__flink_application_configuration

type aws_kinesisanalyticsv2_application__application_configuration__run_configuration__application_restore_configuration

type aws_kinesisanalyticsv2_application__application_configuration__run_configuration__flink_run_configuration

type aws_kinesisanalyticsv2_application__application_configuration__run_configuration

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__input_parallelism

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__input_processing_configuration__input_lambda_processor

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__input_processing_configuration

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__input_schema__record_column

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__input_schema__record_format__mapping_parameters__csv_mapping_parameters

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__input_schema__record_format__mapping_parameters__json_mapping_parameters

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__input_schema__record_format__mapping_parameters

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__input_schema__record_format

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__input_schema

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__input_starting_position_configuration

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__kinesis_firehose_input

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input__kinesis_streams_input

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__input

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__output__destination_schema

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__output__kinesis_firehose_output

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__output__kinesis_streams_output

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__output__lambda_output

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__output

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__reference_data_source__reference_schema__record_column

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__reference_data_source__reference_schema__record_format__mapping_parameters__csv_mapping_parameters

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__reference_data_source__reference_schema__record_format__mapping_parameters__json_mapping_parameters

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__reference_data_source__reference_schema__record_format__mapping_parameters

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__reference_data_source__reference_schema__record_format

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__reference_data_source__reference_schema

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__reference_data_source__s3_reference_data_source

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration__reference_data_source

type aws_kinesisanalyticsv2_application__application_configuration__sql_application_configuration

type aws_kinesisanalyticsv2_application__application_configuration__vpc_configuration

type aws_kinesisanalyticsv2_application__application_configuration
type aws_kinesisanalyticsv2_application__cloudwatch_logging_options
type aws_kinesisanalyticsv2_application__timeouts
type aws_kinesisanalyticsv2_application

val aws_kinesisanalyticsv2_application :
  ?description:string ->
  ?force_stop:bool ->
  ?id:string ->
  ?start_application:bool ->
  ?tags:(string * string) list ->
  ?tags_all:(string * string) list ->
  ?timeouts:aws_kinesisanalyticsv2_application__timeouts ->
  name:string ->
  runtime_environment:string ->
  service_execution_role:string ->
  application_configuration:
    aws_kinesisanalyticsv2_application__application_configuration
    list ->
  cloudwatch_logging_options:
    aws_kinesisanalyticsv2_application__cloudwatch_logging_options
    list ->
  string ->
  unit
