(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_transfer_workflow__on_exception_steps__copy_step_details__destination_file_location__efs_file_location

type aws_transfer_workflow__on_exception_steps__copy_step_details__destination_file_location__s3_file_location

type aws_transfer_workflow__on_exception_steps__copy_step_details__destination_file_location

type aws_transfer_workflow__on_exception_steps__copy_step_details
type aws_transfer_workflow__on_exception_steps__custom_step_details

type aws_transfer_workflow__on_exception_steps__decrypt_step_details__destination_file_location__efs_file_location

type aws_transfer_workflow__on_exception_steps__decrypt_step_details__destination_file_location__s3_file_location

type aws_transfer_workflow__on_exception_steps__decrypt_step_details__destination_file_location

type aws_transfer_workflow__on_exception_steps__decrypt_step_details
type aws_transfer_workflow__on_exception_steps__delete_step_details
type aws_transfer_workflow__on_exception_steps__tag_step_details__tags
type aws_transfer_workflow__on_exception_steps__tag_step_details
type aws_transfer_workflow__on_exception_steps

type aws_transfer_workflow__steps__copy_step_details__destination_file_location__efs_file_location

type aws_transfer_workflow__steps__copy_step_details__destination_file_location__s3_file_location

type aws_transfer_workflow__steps__copy_step_details__destination_file_location

type aws_transfer_workflow__steps__copy_step_details
type aws_transfer_workflow__steps__custom_step_details

type aws_transfer_workflow__steps__decrypt_step_details__destination_file_location__efs_file_location

type aws_transfer_workflow__steps__decrypt_step_details__destination_file_location__s3_file_location

type aws_transfer_workflow__steps__decrypt_step_details__destination_file_location

type aws_transfer_workflow__steps__decrypt_step_details
type aws_transfer_workflow__steps__delete_step_details
type aws_transfer_workflow__steps__tag_step_details__tags
type aws_transfer_workflow__steps__tag_step_details
type aws_transfer_workflow__steps
type aws_transfer_workflow

val aws_transfer_workflow :
  ?description:string ->
  ?tags:(string * string) list ->
  on_exception_steps:aws_transfer_workflow__on_exception_steps list ->
  steps:aws_transfer_workflow__steps list ->
  string ->
  unit
