(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__activity_metrics

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__advanced_cost_optimization_metrics

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__advanced_data_protection_metrics

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__bucket_level__activity_metrics

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__bucket_level__advanced_cost_optimization_metrics

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__bucket_level__advanced_data_protection_metrics

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__bucket_level__detailed_status_code_metrics

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__bucket_level__prefix_level__storage_metrics__selection_criteria

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__bucket_level__prefix_level__storage_metrics

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__bucket_level__prefix_level

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__bucket_level

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level__detailed_status_code_metrics

type aws_s3control_storage_lens_configuration__storage_lens_configuration__account_level

type aws_s3control_storage_lens_configuration__storage_lens_configuration__aws_org

type aws_s3control_storage_lens_configuration__storage_lens_configuration__data_export__cloud_watch_metrics

type aws_s3control_storage_lens_configuration__storage_lens_configuration__data_export__s3_bucket_destination__encryption__sse_kms

type aws_s3control_storage_lens_configuration__storage_lens_configuration__data_export__s3_bucket_destination__encryption__sse_s3

type aws_s3control_storage_lens_configuration__storage_lens_configuration__data_export__s3_bucket_destination__encryption

type aws_s3control_storage_lens_configuration__storage_lens_configuration__data_export__s3_bucket_destination

type aws_s3control_storage_lens_configuration__storage_lens_configuration__data_export

type aws_s3control_storage_lens_configuration__storage_lens_configuration__exclude

type aws_s3control_storage_lens_configuration__storage_lens_configuration__include

type aws_s3control_storage_lens_configuration__storage_lens_configuration

type aws_s3control_storage_lens_configuration

val aws_s3control_storage_lens_configuration :
  ?account_id:string ->
  ?id:string ->
  ?tags:(string * string) list ->
  ?tags_all:(string * string) list ->
  config_id:string ->
  storage_lens_configuration:
    aws_s3control_storage_lens_configuration__storage_lens_configuration
    list ->
  string ->
  unit
