(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_sagemaker_domain__default_space_settings__jupyter_server_app_settings__code_repository

type aws_sagemaker_domain__default_space_settings__jupyter_server_app_settings__default_resource_spec

type aws_sagemaker_domain__default_space_settings__jupyter_server_app_settings

type aws_sagemaker_domain__default_space_settings__kernel_gateway_app_settings__custom_image

type aws_sagemaker_domain__default_space_settings__kernel_gateway_app_settings__default_resource_spec

type aws_sagemaker_domain__default_space_settings__kernel_gateway_app_settings

type aws_sagemaker_domain__default_space_settings

type aws_sagemaker_domain__default_user_settings__canvas_app_settings__direct_deploy_settings

type aws_sagemaker_domain__default_user_settings__canvas_app_settings__identity_provider_oauth_settings

type aws_sagemaker_domain__default_user_settings__canvas_app_settings__kendra_settings

type aws_sagemaker_domain__default_user_settings__canvas_app_settings__model_register_settings

type aws_sagemaker_domain__default_user_settings__canvas_app_settings__time_series_forecasting_settings

type aws_sagemaker_domain__default_user_settings__canvas_app_settings__workspace_settings

type aws_sagemaker_domain__default_user_settings__canvas_app_settings

type aws_sagemaker_domain__default_user_settings__code_editor_app_settings__default_resource_spec

type aws_sagemaker_domain__default_user_settings__code_editor_app_settings

type aws_sagemaker_domain__default_user_settings__custom_file_system_config__efs_file_system_config

type aws_sagemaker_domain__default_user_settings__custom_file_system_config

type aws_sagemaker_domain__default_user_settings__custom_posix_user_config

type aws_sagemaker_domain__default_user_settings__jupyter_lab_app_settings__code_repository

type aws_sagemaker_domain__default_user_settings__jupyter_lab_app_settings__custom_image

type aws_sagemaker_domain__default_user_settings__jupyter_lab_app_settings__default_resource_spec

type aws_sagemaker_domain__default_user_settings__jupyter_lab_app_settings

type aws_sagemaker_domain__default_user_settings__jupyter_server_app_settings__code_repository

type aws_sagemaker_domain__default_user_settings__jupyter_server_app_settings__default_resource_spec

type aws_sagemaker_domain__default_user_settings__jupyter_server_app_settings

type aws_sagemaker_domain__default_user_settings__kernel_gateway_app_settings__custom_image

type aws_sagemaker_domain__default_user_settings__kernel_gateway_app_settings__default_resource_spec

type aws_sagemaker_domain__default_user_settings__kernel_gateway_app_settings

type aws_sagemaker_domain__default_user_settings__r_session_app_settings__custom_image

type aws_sagemaker_domain__default_user_settings__r_session_app_settings__default_resource_spec

type aws_sagemaker_domain__default_user_settings__r_session_app_settings

type aws_sagemaker_domain__default_user_settings__r_studio_server_pro_app_settings

type aws_sagemaker_domain__default_user_settings__sharing_settings

type aws_sagemaker_domain__default_user_settings__space_storage_settings__default_ebs_storage_settings

type aws_sagemaker_domain__default_user_settings__space_storage_settings

type aws_sagemaker_domain__default_user_settings__tensor_board_app_settings__default_resource_spec

type aws_sagemaker_domain__default_user_settings__tensor_board_app_settings

type aws_sagemaker_domain__default_user_settings

type aws_sagemaker_domain__domain_settings__r_studio_server_pro_domain_settings__default_resource_spec

type aws_sagemaker_domain__domain_settings__r_studio_server_pro_domain_settings

type aws_sagemaker_domain__domain_settings
type aws_sagemaker_domain__retention_policy
type aws_sagemaker_domain

val aws_sagemaker_domain :
  ?app_network_access_type:string ->
  ?app_security_group_management:string ->
  ?id:string ->
  ?kms_key_id:string ->
  ?tags:(string * string) list ->
  ?tags_all:(string * string) list ->
  auth_mode:string ->
  domain_name:string ->
  subnet_ids:string list ->
  vpc_id:string ->
  default_space_settings:
    aws_sagemaker_domain__default_space_settings list ->
  default_user_settings:
    aws_sagemaker_domain__default_user_settings list ->
  domain_settings:aws_sagemaker_domain__domain_settings list ->
  retention_policy:aws_sagemaker_domain__retention_policy list ->
  string ->
  unit
