(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_medialive_channel__cdi_input_specification
type aws_medialive_channel__destinations__media_package_settings
type aws_medialive_channel__destinations__multiplex_settings
type aws_medialive_channel__destinations__settings
type aws_medialive_channel__destinations

type aws_medialive_channel__encoder_settings__audio_descriptions__audio_normalization_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__audio_watermark_settings__nielsen_watermarks_settings__nielsen_cbet_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__audio_watermark_settings__nielsen_watermarks_settings__nielsen_naes_ii_nw_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__audio_watermark_settings__nielsen_watermarks_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__audio_watermark_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__codec_settings__aac_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__codec_settings__ac3_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__codec_settings__eac3_atmos_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__codec_settings__eac3_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__codec_settings__mp2_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__codec_settings__pass_through_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__codec_settings__wav_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__codec_settings

type aws_medialive_channel__encoder_settings__audio_descriptions__remix_settings__channel_mappings__input_channel_levels

type aws_medialive_channel__encoder_settings__audio_descriptions__remix_settings__channel_mappings

type aws_medialive_channel__encoder_settings__audio_descriptions__remix_settings

type aws_medialive_channel__encoder_settings__audio_descriptions

type aws_medialive_channel__encoder_settings__avail_blanking__avail_blanking_image

type aws_medialive_channel__encoder_settings__avail_blanking

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__arib_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__burn_in_destination_settings__font

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__burn_in_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__dvb_sub_destination_settings__font

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__dvb_sub_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__ebu_tt_d_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__embedded_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__embedded_plus_scte20_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__rtmp_caption_info_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__scte20_plus_embedded_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__scte27_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__smpte_tt_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__teletext_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__ttml_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings__webvtt_destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions__destination_settings

type aws_medialive_channel__encoder_settings__caption_descriptions

type aws_medialive_channel__encoder_settings__global_configuration__input_loss_behavior__input_loss_image_slate

type aws_medialive_channel__encoder_settings__global_configuration__input_loss_behavior

type aws_medialive_channel__encoder_settings__global_configuration

type aws_medialive_channel__encoder_settings__motion_graphics_configuration__motion_graphics_settings__html_motion_graphics_settings

type aws_medialive_channel__encoder_settings__motion_graphics_configuration__motion_graphics_settings

type aws_medialive_channel__encoder_settings__motion_graphics_configuration

type aws_medialive_channel__encoder_settings__nielsen_configuration

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__archive_group_settings__archive_cdn_settings__archive_s3_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__archive_group_settings__archive_cdn_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__archive_group_settings__destination

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__archive_group_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__frame_capture_group_settings__destination

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__frame_capture_group_settings__frame_capture_cdn_settings__frame_capture_s3_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__frame_capture_group_settings__frame_capture_cdn_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__frame_capture_group_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__caption_language_mappings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__destination

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__hls_cdn_settings__hls_akamai_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__hls_cdn_settings__hls_basic_put_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__hls_cdn_settings__hls_media_store_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__hls_cdn_settings__hls_s3_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__hls_cdn_settings__hls_webdav_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__hls_cdn_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__key_provider_settings__static_key_settings__key_provider_server

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__key_provider_settings__static_key_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings__key_provider_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__hls_group_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__media_package_group_settings__destination

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__media_package_group_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__ms_smooth_group_settings__destination

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__ms_smooth_group_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__multiplex_group_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__rtmp_group_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings__udp_group_settings

type aws_medialive_channel__encoder_settings__output_groups__output_group_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__archive_output_settings__container_settings__m2ts_settings__dvb_nit_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__archive_output_settings__container_settings__m2ts_settings__dvb_sdt_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__archive_output_settings__container_settings__m2ts_settings__dvb_tdt_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__archive_output_settings__container_settings__m2ts_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__archive_output_settings__container_settings__raw_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__archive_output_settings__container_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__archive_output_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__frame_capture_output_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__hls_output_settings__hls_settings__audio_only_hls_settings__audio_only_image

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__hls_output_settings__hls_settings__audio_only_hls_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__hls_output_settings__hls_settings__fmp4_hls_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__hls_output_settings__hls_settings__frame_capture_hls_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__hls_output_settings__hls_settings__standard_hls_settings__m3u8_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__hls_output_settings__hls_settings__standard_hls_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__hls_output_settings__hls_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__hls_output_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__media_package_output_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__ms_smooth_output_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__multiplex_output_settings__destination

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__multiplex_output_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__rtmp_output_settings__destination

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__rtmp_output_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__udp_output_settings__container_settings__m2ts_settings__dvb_nit_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__udp_output_settings__container_settings__m2ts_settings__dvb_sdt_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__udp_output_settings__container_settings__m2ts_settings__dvb_tdt_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__udp_output_settings__container_settings__m2ts_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__udp_output_settings__container_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__udp_output_settings__destination

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__udp_output_settings__fec_output_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings__udp_output_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs__output_settings

type aws_medialive_channel__encoder_settings__output_groups__outputs
type aws_medialive_channel__encoder_settings__output_groups
type aws_medialive_channel__encoder_settings__timecode_config

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__frame_capture_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h264_settings__filter_settings__temporal_filter_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h264_settings__filter_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h264_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h265_settings__color_space_settings__color_space_passthrough_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h265_settings__color_space_settings__dolby_vision81_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h265_settings__color_space_settings__hdr10_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h265_settings__color_space_settings__rec601_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h265_settings__color_space_settings__rec709_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h265_settings__color_space_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h265_settings__filter_settings__temporal_filter_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h265_settings__filter_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h265_settings__timecode_burnin_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings__h265_settings

type aws_medialive_channel__encoder_settings__video_descriptions__codec_settings

type aws_medialive_channel__encoder_settings__video_descriptions
type aws_medialive_channel__encoder_settings

type aws_medialive_channel__input_attachments__automatic_input_failover_settings__failover_condition__failover_condition_settings__audio_silence_settings

type aws_medialive_channel__input_attachments__automatic_input_failover_settings__failover_condition__failover_condition_settings__input_loss_settings

type aws_medialive_channel__input_attachments__automatic_input_failover_settings__failover_condition__failover_condition_settings__video_black_settings

type aws_medialive_channel__input_attachments__automatic_input_failover_settings__failover_condition__failover_condition_settings

type aws_medialive_channel__input_attachments__automatic_input_failover_settings__failover_condition

type aws_medialive_channel__input_attachments__automatic_input_failover_settings

type aws_medialive_channel__input_attachments__input_settings__audio_selector__selector_settings__audio_hls_rendition_selection

type aws_medialive_channel__input_attachments__input_settings__audio_selector__selector_settings__audio_language_selection

type aws_medialive_channel__input_attachments__input_settings__audio_selector__selector_settings__audio_pid_selection

type aws_medialive_channel__input_attachments__input_settings__audio_selector__selector_settings__audio_track_selection__dolby_e_decode

type aws_medialive_channel__input_attachments__input_settings__audio_selector__selector_settings__audio_track_selection__tracks

type aws_medialive_channel__input_attachments__input_settings__audio_selector__selector_settings__audio_track_selection

type aws_medialive_channel__input_attachments__input_settings__audio_selector__selector_settings

type aws_medialive_channel__input_attachments__input_settings__audio_selector

type aws_medialive_channel__input_attachments__input_settings__caption_selector__selector_settings__ancillary_source_settings

type aws_medialive_channel__input_attachments__input_settings__caption_selector__selector_settings__arib_source_settings

type aws_medialive_channel__input_attachments__input_settings__caption_selector__selector_settings__dvb_sub_source_settings

type aws_medialive_channel__input_attachments__input_settings__caption_selector__selector_settings__embedded_source_settings

type aws_medialive_channel__input_attachments__input_settings__caption_selector__selector_settings__scte20_source_settings

type aws_medialive_channel__input_attachments__input_settings__caption_selector__selector_settings__scte27_source_settings

type aws_medialive_channel__input_attachments__input_settings__caption_selector__selector_settings__teletext_source_settings__output_rectangle

type aws_medialive_channel__input_attachments__input_settings__caption_selector__selector_settings__teletext_source_settings

type aws_medialive_channel__input_attachments__input_settings__caption_selector__selector_settings

type aws_medialive_channel__input_attachments__input_settings__caption_selector

type aws_medialive_channel__input_attachments__input_settings__network_input_settings__hls_input_settings

type aws_medialive_channel__input_attachments__input_settings__network_input_settings

type aws_medialive_channel__input_attachments__input_settings__video_selector

type aws_medialive_channel__input_attachments__input_settings
type aws_medialive_channel__input_attachments
type aws_medialive_channel__input_specification
type aws_medialive_channel__maintenance
type aws_medialive_channel__timeouts
type aws_medialive_channel__vpc
type aws_medialive_channel

val aws_medialive_channel :
  ?id:string prop ->
  ?log_level:string prop ->
  ?role_arn:string prop ->
  ?start_channel:bool prop ->
  ?tags:(string * string prop) list ->
  ?tags_all:(string * string prop) list ->
  ?timeouts:aws_medialive_channel__timeouts ->
  channel_class:string prop ->
  name:string prop ->
  cdi_input_specification:
    aws_medialive_channel__cdi_input_specification list ->
  destinations:aws_medialive_channel__destinations list ->
  encoder_settings:aws_medialive_channel__encoder_settings list ->
  input_attachments:aws_medialive_channel__input_attachments list ->
  input_specification:aws_medialive_channel__input_specification list ->
  maintenance:aws_medialive_channel__maintenance list ->
  vpc:aws_medialive_channel__vpc list ->
  string ->
  unit
