(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_cognito_risk_configuration__account_takeover_risk_configuration__actions__high_action

type aws_cognito_risk_configuration__account_takeover_risk_configuration__actions__low_action

type aws_cognito_risk_configuration__account_takeover_risk_configuration__actions__medium_action

type aws_cognito_risk_configuration__account_takeover_risk_configuration__actions

type aws_cognito_risk_configuration__account_takeover_risk_configuration__notify_configuration__block_email

type aws_cognito_risk_configuration__account_takeover_risk_configuration__notify_configuration__mfa_email

type aws_cognito_risk_configuration__account_takeover_risk_configuration__notify_configuration__no_action_email

type aws_cognito_risk_configuration__account_takeover_risk_configuration__notify_configuration

type aws_cognito_risk_configuration__account_takeover_risk_configuration

type aws_cognito_risk_configuration__compromised_credentials_risk_configuration__actions

type aws_cognito_risk_configuration__compromised_credentials_risk_configuration

type aws_cognito_risk_configuration__risk_exception_configuration
type aws_cognito_risk_configuration

val aws_cognito_risk_configuration :
  ?client_id:string prop ->
  ?id:string prop ->
  user_pool_id:string prop ->
  account_takeover_risk_configuration:
    aws_cognito_risk_configuration__account_takeover_risk_configuration
    list ->
  compromised_credentials_risk_configuration:
    aws_cognito_risk_configuration__compromised_credentials_risk_configuration
    list ->
  risk_exception_configuration:
    aws_cognito_risk_configuration__risk_exception_configuration list ->
  string ->
  unit
