(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_kinesis_firehose_delivery_stream__elasticsearch_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__elasticsearch_configuration__processing_configuration__processors__parameters

type aws_kinesis_firehose_delivery_stream__elasticsearch_configuration__processing_configuration__processors

type aws_kinesis_firehose_delivery_stream__elasticsearch_configuration__processing_configuration

type aws_kinesis_firehose_delivery_stream__elasticsearch_configuration__s3_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__elasticsearch_configuration__s3_configuration

type aws_kinesis_firehose_delivery_stream__elasticsearch_configuration__vpc_config

type aws_kinesis_firehose_delivery_stream__elasticsearch_configuration

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__data_format_conversion_configuration__input_format_configuration__deserializer__hive_json_ser_de

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__data_format_conversion_configuration__input_format_configuration__deserializer__open_x_json_ser_de

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__data_format_conversion_configuration__input_format_configuration__deserializer

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__data_format_conversion_configuration__input_format_configuration

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__data_format_conversion_configuration__output_format_configuration__serializer__orc_ser_de

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__data_format_conversion_configuration__output_format_configuration__serializer__parquet_ser_de

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__data_format_conversion_configuration__output_format_configuration__serializer

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__data_format_conversion_configuration__output_format_configuration

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__data_format_conversion_configuration__schema_configuration

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__data_format_conversion_configuration

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__dynamic_partitioning_configuration

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__processing_configuration__processors__parameters

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__processing_configuration__processors

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__processing_configuration

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__s3_backup_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration__s3_backup_configuration

type aws_kinesis_firehose_delivery_stream__extended_s3_configuration

type aws_kinesis_firehose_delivery_stream__http_endpoint_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__http_endpoint_configuration__processing_configuration__processors__parameters

type aws_kinesis_firehose_delivery_stream__http_endpoint_configuration__processing_configuration__processors

type aws_kinesis_firehose_delivery_stream__http_endpoint_configuration__processing_configuration

type aws_kinesis_firehose_delivery_stream__http_endpoint_configuration__request_configuration__common_attributes

type aws_kinesis_firehose_delivery_stream__http_endpoint_configuration__request_configuration

type aws_kinesis_firehose_delivery_stream__http_endpoint_configuration__s3_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__http_endpoint_configuration__s3_configuration

type aws_kinesis_firehose_delivery_stream__http_endpoint_configuration

type aws_kinesis_firehose_delivery_stream__kinesis_source_configuration

type aws_kinesis_firehose_delivery_stream__msk_source_configuration__authentication_configuration

type aws_kinesis_firehose_delivery_stream__msk_source_configuration

type aws_kinesis_firehose_delivery_stream__opensearch_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__opensearch_configuration__document_id_options

type aws_kinesis_firehose_delivery_stream__opensearch_configuration__processing_configuration__processors__parameters

type aws_kinesis_firehose_delivery_stream__opensearch_configuration__processing_configuration__processors

type aws_kinesis_firehose_delivery_stream__opensearch_configuration__processing_configuration

type aws_kinesis_firehose_delivery_stream__opensearch_configuration__s3_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__opensearch_configuration__s3_configuration

type aws_kinesis_firehose_delivery_stream__opensearch_configuration__vpc_config

type aws_kinesis_firehose_delivery_stream__opensearch_configuration

type aws_kinesis_firehose_delivery_stream__opensearchserverless_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__opensearchserverless_configuration__processing_configuration__processors__parameters

type aws_kinesis_firehose_delivery_stream__opensearchserverless_configuration__processing_configuration__processors

type aws_kinesis_firehose_delivery_stream__opensearchserverless_configuration__processing_configuration

type aws_kinesis_firehose_delivery_stream__opensearchserverless_configuration__s3_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__opensearchserverless_configuration__s3_configuration

type aws_kinesis_firehose_delivery_stream__opensearchserverless_configuration__vpc_config

type aws_kinesis_firehose_delivery_stream__opensearchserverless_configuration

type aws_kinesis_firehose_delivery_stream__redshift_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__redshift_configuration__processing_configuration__processors__parameters

type aws_kinesis_firehose_delivery_stream__redshift_configuration__processing_configuration__processors

type aws_kinesis_firehose_delivery_stream__redshift_configuration__processing_configuration

type aws_kinesis_firehose_delivery_stream__redshift_configuration__s3_backup_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__redshift_configuration__s3_backup_configuration

type aws_kinesis_firehose_delivery_stream__redshift_configuration__s3_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__redshift_configuration__s3_configuration

type aws_kinesis_firehose_delivery_stream__redshift_configuration
type aws_kinesis_firehose_delivery_stream__server_side_encryption

type aws_kinesis_firehose_delivery_stream__splunk_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__splunk_configuration__processing_configuration__processors__parameters

type aws_kinesis_firehose_delivery_stream__splunk_configuration__processing_configuration__processors

type aws_kinesis_firehose_delivery_stream__splunk_configuration__processing_configuration

type aws_kinesis_firehose_delivery_stream__splunk_configuration__s3_configuration__cloudwatch_logging_options

type aws_kinesis_firehose_delivery_stream__splunk_configuration__s3_configuration

type aws_kinesis_firehose_delivery_stream__splunk_configuration
type aws_kinesis_firehose_delivery_stream__timeouts
type aws_kinesis_firehose_delivery_stream

val aws_kinesis_firehose_delivery_stream :
  ?arn:string ->
  ?destination_id:string ->
  ?id:string ->
  ?tags:(string * string) list ->
  ?tags_all:(string * string) list ->
  ?version_id:string ->
  ?timeouts:aws_kinesis_firehose_delivery_stream__timeouts ->
  destination:string ->
  name:string ->
  elasticsearch_configuration:
    aws_kinesis_firehose_delivery_stream__elasticsearch_configuration
    list ->
  extended_s3_configuration:
    aws_kinesis_firehose_delivery_stream__extended_s3_configuration
    list ->
  http_endpoint_configuration:
    aws_kinesis_firehose_delivery_stream__http_endpoint_configuration
    list ->
  kinesis_source_configuration:
    aws_kinesis_firehose_delivery_stream__kinesis_source_configuration
    list ->
  msk_source_configuration:
    aws_kinesis_firehose_delivery_stream__msk_source_configuration
    list ->
  opensearch_configuration:
    aws_kinesis_firehose_delivery_stream__opensearch_configuration
    list ->
  opensearchserverless_configuration:
    aws_kinesis_firehose_delivery_stream__opensearchserverless_configuration
    list ->
  redshift_configuration:
    aws_kinesis_firehose_delivery_stream__redshift_configuration list ->
  server_side_encryption:
    aws_kinesis_firehose_delivery_stream__server_side_encryption list ->
  splunk_configuration:
    aws_kinesis_firehose_delivery_stream__splunk_configuration list ->
  string ->
  unit
