(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type azurerm_media_streaming_policy__common_encryption_cbcs__clear_key_encryption

type azurerm_media_streaming_policy__common_encryption_cbcs__default_content_key

type azurerm_media_streaming_policy__common_encryption_cbcs__drm_fairplay

type azurerm_media_streaming_policy__common_encryption_cbcs__enabled_protocols

type azurerm_media_streaming_policy__common_encryption_cbcs

type azurerm_media_streaming_policy__common_encryption_cenc__clear_key_encryption

type azurerm_media_streaming_policy__common_encryption_cenc__clear_track__condition

type azurerm_media_streaming_policy__common_encryption_cenc__clear_track

type azurerm_media_streaming_policy__common_encryption_cenc__content_key_to_track_mapping__track__condition

type azurerm_media_streaming_policy__common_encryption_cenc__content_key_to_track_mapping__track

type azurerm_media_streaming_policy__common_encryption_cenc__content_key_to_track_mapping

type azurerm_media_streaming_policy__common_encryption_cenc__default_content_key

type azurerm_media_streaming_policy__common_encryption_cenc__drm_playready

type azurerm_media_streaming_policy__common_encryption_cenc__enabled_protocols

type azurerm_media_streaming_policy__common_encryption_cenc

type azurerm_media_streaming_policy__envelope_encryption__default_content_key

type azurerm_media_streaming_policy__envelope_encryption__enabled_protocols

type azurerm_media_streaming_policy__envelope_encryption
type azurerm_media_streaming_policy__no_encryption_enabled_protocols
type azurerm_media_streaming_policy__timeouts
type azurerm_media_streaming_policy

type t = private {
  default_content_key_policy_name : string prop;
  id : string prop;
  media_services_account_name : string prop;
  name : string prop;
  resource_group_name : string prop;
}

val azurerm_media_streaming_policy :
  ?default_content_key_policy_name:string prop ->
  ?id:string prop ->
  ?timeouts:azurerm_media_streaming_policy__timeouts ->
  media_services_account_name:string prop ->
  name:string prop ->
  resource_group_name:string prop ->
  common_encryption_cbcs:
    azurerm_media_streaming_policy__common_encryption_cbcs list ->
  common_encryption_cenc:
    azurerm_media_streaming_policy__common_encryption_cenc list ->
  envelope_encryption:
    azurerm_media_streaming_policy__envelope_encryption list ->
  no_encryption_enabled_protocols:
    azurerm_media_streaming_policy__no_encryption_enabled_protocols
    list ->
  string ->
  t
