(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type azurerm_workloads_sap_three_tier_virtual_instance__identity

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__application_server_configuration__virtual_machine_configuration__image

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__application_server_configuration__virtual_machine_configuration__os_profile

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__application_server_configuration__virtual_machine_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__application_server_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__central_server_configuration__virtual_machine_configuration__image

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__central_server_configuration__virtual_machine_configuration__os_profile

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__central_server_configuration__virtual_machine_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__central_server_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__database_server_configuration__disk_volume_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__database_server_configuration__virtual_machine_configuration__image

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__database_server_configuration__virtual_machine_configuration__os_profile

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__database_server_configuration__virtual_machine_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__database_server_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__application_server__virtual_machine__data_disk

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__application_server__virtual_machine

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__application_server

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__central_server__load_balancer

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__central_server__virtual_machine__data_disk

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__central_server__virtual_machine

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__central_server

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__database_server__load_balancer

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__database_server__virtual_machine__data_disk

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__database_server__virtual_machine

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__database_server

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__shared_storage

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__transport_create_and_mount

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__timeouts
type azurerm_workloads_sap_three_tier_virtual_instance

type t = private {
  app_location : string prop;
  environment : string prop;
  id : string prop;
  location : string prop;
  managed_resource_group_name : string prop;
  name : string prop;
  resource_group_name : string prop;
  sap_fqdn : string prop;
  sap_product : string prop;
  tags : (string * string) list prop;
}

val azurerm_workloads_sap_three_tier_virtual_instance :
  ?id:string prop ->
  ?managed_resource_group_name:string prop ->
  ?tags:(string * string prop) list ->
  ?timeouts:
    azurerm_workloads_sap_three_tier_virtual_instance__timeouts ->
  app_location:string prop ->
  environment:string prop ->
  location:string prop ->
  name:string prop ->
  resource_group_name:string prop ->
  sap_fqdn:string prop ->
  sap_product:string prop ->
  identity:
    azurerm_workloads_sap_three_tier_virtual_instance__identity list ->
  three_tier_configuration:
    azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration
    list ->
  string ->
  t
