(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type azurerm_media_transform__output__audio_analyzer_preset

type azurerm_media_transform__output__builtin_preset__preset_configuration

type azurerm_media_transform__output__builtin_preset
type azurerm_media_transform__output__custom_preset__codec__aac_audio
type azurerm_media_transform__output__custom_preset__codec__copy_audio
type azurerm_media_transform__output__custom_preset__codec__copy_video
type azurerm_media_transform__output__custom_preset__codec__dd_audio

type azurerm_media_transform__output__custom_preset__codec__h264_video__layer

type azurerm_media_transform__output__custom_preset__codec__h264_video

type azurerm_media_transform__output__custom_preset__codec__h265_video__layer

type azurerm_media_transform__output__custom_preset__codec__h265_video

type azurerm_media_transform__output__custom_preset__codec__jpg_image__layer

type azurerm_media_transform__output__custom_preset__codec__jpg_image

type azurerm_media_transform__output__custom_preset__codec__png_image__layer

type azurerm_media_transform__output__custom_preset__codec__png_image
type azurerm_media_transform__output__custom_preset__codec

type azurerm_media_transform__output__custom_preset__filter__crop_rectangle

type azurerm_media_transform__output__custom_preset__filter__deinterlace

type azurerm_media_transform__output__custom_preset__filter__fade_in
type azurerm_media_transform__output__custom_preset__filter__fade_out

type azurerm_media_transform__output__custom_preset__filter__overlay__audio

type azurerm_media_transform__output__custom_preset__filter__overlay__video__crop_rectangle

type azurerm_media_transform__output__custom_preset__filter__overlay__video__position

type azurerm_media_transform__output__custom_preset__filter__overlay__video

type azurerm_media_transform__output__custom_preset__filter__overlay
type azurerm_media_transform__output__custom_preset__filter
type azurerm_media_transform__output__custom_preset__format__jpg

type azurerm_media_transform__output__custom_preset__format__mp4__output_file

type azurerm_media_transform__output__custom_preset__format__mp4
type azurerm_media_transform__output__custom_preset__format__png

type azurerm_media_transform__output__custom_preset__format__transport_stream__output_file

type azurerm_media_transform__output__custom_preset__format__transport_stream

type azurerm_media_transform__output__custom_preset__format
type azurerm_media_transform__output__custom_preset
type azurerm_media_transform__output__face_detector_preset
type azurerm_media_transform__output__video_analyzer_preset
type azurerm_media_transform__output
type azurerm_media_transform__timeouts
type azurerm_media_transform

val azurerm_media_transform :
  ?description:string prop ->
  ?id:string prop ->
  ?timeouts:azurerm_media_transform__timeouts ->
  media_services_account_name:string prop ->
  name:string prop ->
  resource_group_name:string prop ->
  output:azurerm_media_transform__output list ->
  string ->
  unit
