(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type azurerm_cdn_frontdoor_rule__actions__request_header_action
type azurerm_cdn_frontdoor_rule__actions__response_header_action

type azurerm_cdn_frontdoor_rule__actions__route_configuration_override_action

type azurerm_cdn_frontdoor_rule__actions__url_redirect_action
type azurerm_cdn_frontdoor_rule__actions__url_rewrite_action
type azurerm_cdn_frontdoor_rule__actions
type azurerm_cdn_frontdoor_rule__conditions__client_port_condition
type azurerm_cdn_frontdoor_rule__conditions__cookies_condition
type azurerm_cdn_frontdoor_rule__conditions__host_name_condition
type azurerm_cdn_frontdoor_rule__conditions__http_version_condition
type azurerm_cdn_frontdoor_rule__conditions__is_device_condition
type azurerm_cdn_frontdoor_rule__conditions__post_args_condition
type azurerm_cdn_frontdoor_rule__conditions__query_string_condition
type azurerm_cdn_frontdoor_rule__conditions__remote_address_condition
type azurerm_cdn_frontdoor_rule__conditions__request_body_condition
type azurerm_cdn_frontdoor_rule__conditions__request_header_condition
type azurerm_cdn_frontdoor_rule__conditions__request_method_condition
type azurerm_cdn_frontdoor_rule__conditions__request_scheme_condition
type azurerm_cdn_frontdoor_rule__conditions__request_uri_condition
type azurerm_cdn_frontdoor_rule__conditions__server_port_condition
type azurerm_cdn_frontdoor_rule__conditions__socket_address_condition
type azurerm_cdn_frontdoor_rule__conditions__ssl_protocol_condition

type azurerm_cdn_frontdoor_rule__conditions__url_file_extension_condition

type azurerm_cdn_frontdoor_rule__conditions__url_filename_condition
type azurerm_cdn_frontdoor_rule__conditions__url_path_condition
type azurerm_cdn_frontdoor_rule__conditions
type azurerm_cdn_frontdoor_rule__timeouts
type azurerm_cdn_frontdoor_rule

val azurerm_cdn_frontdoor_rule :
  ?behavior_on_match:string ->
  ?timeouts:azurerm_cdn_frontdoor_rule__timeouts ->
  cdn_frontdoor_rule_set_id:string ->
  name:string ->
  order:float ->
  actions:azurerm_cdn_frontdoor_rule__actions list ->
  conditions:azurerm_cdn_frontdoor_rule__conditions list ->
  string ->
  unit
