(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type azurerm_workloads_sap_three_tier_virtual_instance__identity

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__application_server_configuration__virtual_machine_configuration__image

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__application_server_configuration__virtual_machine_configuration__os_profile

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__application_server_configuration__virtual_machine_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__application_server_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__central_server_configuration__virtual_machine_configuration__image

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__central_server_configuration__virtual_machine_configuration__os_profile

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__central_server_configuration__virtual_machine_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__central_server_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__database_server_configuration__disk_volume_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__database_server_configuration__virtual_machine_configuration__image

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__database_server_configuration__virtual_machine_configuration__os_profile

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__database_server_configuration__virtual_machine_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__database_server_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__application_server__virtual_machine__data_disk

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__application_server__virtual_machine

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__application_server

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__central_server__load_balancer

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__central_server__virtual_machine__data_disk

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__central_server__virtual_machine

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__central_server

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__database_server__load_balancer

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__database_server__virtual_machine__data_disk

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__database_server__virtual_machine

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__database_server

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names__shared_storage

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__resource_names

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration__transport_create_and_mount

type azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration

type azurerm_workloads_sap_three_tier_virtual_instance__timeouts
type azurerm_workloads_sap_three_tier_virtual_instance

val azurerm_workloads_sap_three_tier_virtual_instance :
  ?managed_resource_group_name:string ->
  ?tags:(string * string) list ->
  ?timeouts:
    azurerm_workloads_sap_three_tier_virtual_instance__timeouts ->
  app_location:string ->
  environment:string ->
  location:string ->
  name:string ->
  resource_group_name:string ->
  sap_fqdn:string ->
  sap_product:string ->
  identity:
    azurerm_workloads_sap_three_tier_virtual_instance__identity list ->
  three_tier_configuration:
    azurerm_workloads_sap_three_tier_virtual_instance__three_tier_configuration
    list ->
  string ->
  unit
