(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_capacity_metric_specification__metric_data_queries__metric_stat__metric__dimensions

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_capacity_metric_specification__metric_data_queries__metric_stat__metric

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_capacity_metric_specification__metric_data_queries__metric_stat

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_capacity_metric_specification__metric_data_queries

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_capacity_metric_specification

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_load_metric_specification__metric_data_queries__metric_stat__metric__dimensions

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_load_metric_specification__metric_data_queries__metric_stat__metric

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_load_metric_specification__metric_data_queries__metric_stat

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_load_metric_specification__metric_data_queries

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_load_metric_specification

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_scaling_metric_specification__metric_data_queries__metric_stat__metric__dimensions

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_scaling_metric_specification__metric_data_queries__metric_stat__metric

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_scaling_metric_specification__metric_data_queries__metric_stat

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_scaling_metric_specification__metric_data_queries

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__customized_scaling_metric_specification

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__predefined_load_metric_specification

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__predefined_metric_pair_specification

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification__predefined_scaling_metric_specification

type aws_autoscaling_policy__predictive_scaling_configuration__metric_specification

type aws_autoscaling_policy__predictive_scaling_configuration
type aws_autoscaling_policy__step_adjustment

type aws_autoscaling_policy__target_tracking_configuration__customized_metric_specification__metric_dimension

type aws_autoscaling_policy__target_tracking_configuration__customized_metric_specification__metrics__metric_stat__metric__dimensions

type aws_autoscaling_policy__target_tracking_configuration__customized_metric_specification__metrics__metric_stat__metric

type aws_autoscaling_policy__target_tracking_configuration__customized_metric_specification__metrics__metric_stat

type aws_autoscaling_policy__target_tracking_configuration__customized_metric_specification__metrics

type aws_autoscaling_policy__target_tracking_configuration__customized_metric_specification

type aws_autoscaling_policy__target_tracking_configuration__predefined_metric_specification

type aws_autoscaling_policy__target_tracking_configuration
type aws_autoscaling_policy

type t = private {
  adjustment_type : string prop;
  arn : string prop;
  autoscaling_group_name : string prop;
  cooldown : float prop;
  enabled : bool prop;
  estimated_instance_warmup : float prop;
  id : string prop;
  metric_aggregation_type : string prop;
  min_adjustment_magnitude : float prop;
  name : string prop;
  policy_type : string prop;
  scaling_adjustment : float prop;
}

val aws_autoscaling_policy :
  ?adjustment_type:string prop ->
  ?cooldown:float prop ->
  ?enabled:bool prop ->
  ?estimated_instance_warmup:float prop ->
  ?id:string prop ->
  ?metric_aggregation_type:string prop ->
  ?min_adjustment_magnitude:float prop ->
  ?policy_type:string prop ->
  ?scaling_adjustment:float prop ->
  autoscaling_group_name:string prop ->
  name:string prop ->
  predictive_scaling_configuration:
    aws_autoscaling_policy__predictive_scaling_configuration list ->
  step_adjustment:aws_autoscaling_policy__step_adjustment list ->
  target_tracking_configuration:
    aws_autoscaling_policy__target_tracking_configuration list ->
  string ->
  t
