(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_securityhub_insight__filters__aws_account_id
type aws_securityhub_insight__filters__company_name
type aws_securityhub_insight__filters__compliance_status
type aws_securityhub_insight__filters__confidence
type aws_securityhub_insight__filters__created_at__date_range
type aws_securityhub_insight__filters__created_at
type aws_securityhub_insight__filters__criticality
type aws_securityhub_insight__filters__description

type aws_securityhub_insight__filters__finding_provider_fields_confidence

type aws_securityhub_insight__filters__finding_provider_fields_criticality

type aws_securityhub_insight__filters__finding_provider_fields_related_findings_id

type aws_securityhub_insight__filters__finding_provider_fields_related_findings_product_arn

type aws_securityhub_insight__filters__finding_provider_fields_severity_label

type aws_securityhub_insight__filters__finding_provider_fields_severity_original

type aws_securityhub_insight__filters__finding_provider_fields_types
type aws_securityhub_insight__filters__first_observed_at__date_range
type aws_securityhub_insight__filters__first_observed_at
type aws_securityhub_insight__filters__generator_id
type aws_securityhub_insight__filters__id
type aws_securityhub_insight__filters__keyword
type aws_securityhub_insight__filters__last_observed_at__date_range
type aws_securityhub_insight__filters__last_observed_at
type aws_securityhub_insight__filters__malware_name
type aws_securityhub_insight__filters__malware_path
type aws_securityhub_insight__filters__malware_state
type aws_securityhub_insight__filters__malware_type
type aws_securityhub_insight__filters__network_destination_domain
type aws_securityhub_insight__filters__network_destination_ipv4
type aws_securityhub_insight__filters__network_destination_ipv6
type aws_securityhub_insight__filters__network_destination_port
type aws_securityhub_insight__filters__network_direction
type aws_securityhub_insight__filters__network_protocol
type aws_securityhub_insight__filters__network_source_domain
type aws_securityhub_insight__filters__network_source_ipv4
type aws_securityhub_insight__filters__network_source_ipv6
type aws_securityhub_insight__filters__network_source_mac
type aws_securityhub_insight__filters__network_source_port
type aws_securityhub_insight__filters__note_text
type aws_securityhub_insight__filters__note_updated_at__date_range
type aws_securityhub_insight__filters__note_updated_at
type aws_securityhub_insight__filters__note_updated_by
type aws_securityhub_insight__filters__process_launched_at__date_range
type aws_securityhub_insight__filters__process_launched_at
type aws_securityhub_insight__filters__process_name
type aws_securityhub_insight__filters__process_parent_pid
type aws_securityhub_insight__filters__process_path
type aws_securityhub_insight__filters__process_pid

type aws_securityhub_insight__filters__process_terminated_at__date_range

type aws_securityhub_insight__filters__process_terminated_at
type aws_securityhub_insight__filters__product_arn
type aws_securityhub_insight__filters__product_fields
type aws_securityhub_insight__filters__product_name
type aws_securityhub_insight__filters__recommendation_text
type aws_securityhub_insight__filters__record_state
type aws_securityhub_insight__filters__related_findings_id
type aws_securityhub_insight__filters__related_findings_product_arn

type aws_securityhub_insight__filters__resource_aws_ec2_instance_iam_instance_profile_arn

type aws_securityhub_insight__filters__resource_aws_ec2_instance_image_id

type aws_securityhub_insight__filters__resource_aws_ec2_instance_ipv4_addresses

type aws_securityhub_insight__filters__resource_aws_ec2_instance_ipv6_addresses

type aws_securityhub_insight__filters__resource_aws_ec2_instance_key_name

type aws_securityhub_insight__filters__resource_aws_ec2_instance_launched_at__date_range

type aws_securityhub_insight__filters__resource_aws_ec2_instance_launched_at

type aws_securityhub_insight__filters__resource_aws_ec2_instance_subnet_id

type aws_securityhub_insight__filters__resource_aws_ec2_instance_type

type aws_securityhub_insight__filters__resource_aws_ec2_instance_vpc_id

type aws_securityhub_insight__filters__resource_aws_iam_access_key_created_at__date_range

type aws_securityhub_insight__filters__resource_aws_iam_access_key_created_at

type aws_securityhub_insight__filters__resource_aws_iam_access_key_status

type aws_securityhub_insight__filters__resource_aws_iam_access_key_user_name

type aws_securityhub_insight__filters__resource_aws_s3_bucket_owner_id

type aws_securityhub_insight__filters__resource_aws_s3_bucket_owner_name

type aws_securityhub_insight__filters__resource_container_image_id
type aws_securityhub_insight__filters__resource_container_image_name

type aws_securityhub_insight__filters__resource_container_launched_at__date_range

type aws_securityhub_insight__filters__resource_container_launched_at
type aws_securityhub_insight__filters__resource_container_name
type aws_securityhub_insight__filters__resource_details_other
type aws_securityhub_insight__filters__resource_id
type aws_securityhub_insight__filters__resource_partition
type aws_securityhub_insight__filters__resource_region
type aws_securityhub_insight__filters__resource_tags
type aws_securityhub_insight__filters__resource_type
type aws_securityhub_insight__filters__severity_label
type aws_securityhub_insight__filters__source_url
type aws_securityhub_insight__filters__threat_intel_indicator_category

type aws_securityhub_insight__filters__threat_intel_indicator_last_observed_at__date_range

type aws_securityhub_insight__filters__threat_intel_indicator_last_observed_at

type aws_securityhub_insight__filters__threat_intel_indicator_source

type aws_securityhub_insight__filters__threat_intel_indicator_source_url

type aws_securityhub_insight__filters__threat_intel_indicator_type
type aws_securityhub_insight__filters__threat_intel_indicator_value
type aws_securityhub_insight__filters__title
type aws_securityhub_insight__filters__type
type aws_securityhub_insight__filters__updated_at__date_range
type aws_securityhub_insight__filters__updated_at
type aws_securityhub_insight__filters__user_defined_values
type aws_securityhub_insight__filters__verification_state
type aws_securityhub_insight__filters__workflow_status
type aws_securityhub_insight__filters
type aws_securityhub_insight

type t = private {
  arn : string prop;
  group_by_attribute : string prop;
  id : string prop;
  name : string prop;
}

val aws_securityhub_insight :
  ?id:string prop ->
  group_by_attribute:string prop ->
  name:string prop ->
  filters:aws_securityhub_insight__filters list ->
  string ->
  t
