(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf_core

(** RESOURCE SERIALIZATION *)

type multiple_values_setting

val multiple_values_setting :
  ?allow_multiple_values:bool prop -> unit -> multiple_values_setting

type obfuscation_setting

val obfuscation_setting :
  obfuscation_setting_type:string prop -> unit -> obfuscation_setting

type timeouts

val timeouts :
  ?create:string prop ->
  ?delete:string prop ->
  ?update:string prop ->
  unit ->
  timeouts

type value_elicitation_setting__default_value_specification__default_value_list

val value_elicitation_setting__default_value_specification__default_value_list :
  default_value:string prop ->
  unit ->
  value_elicitation_setting__default_value_specification__default_value_list

type value_elicitation_setting__default_value_specification

val value_elicitation_setting__default_value_specification :
  ?default_value_list:
    value_elicitation_setting__default_value_specification__default_value_list
    list ->
  unit ->
  value_elicitation_setting__default_value_specification

type value_elicitation_setting__prompt_specification__message_group__message__custom_playload

val value_elicitation_setting__prompt_specification__message_group__message__custom_playload :
  value:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__message__custom_playload

type value_elicitation_setting__prompt_specification__message_group__message__image_response_card__button

val value_elicitation_setting__prompt_specification__message_group__message__image_response_card__button :
  text:string prop ->
  value:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__message__image_response_card__button

type value_elicitation_setting__prompt_specification__message_group__message__image_response_card

val value_elicitation_setting__prompt_specification__message_group__message__image_response_card :
  ?image_url:string prop ->
  ?subtitle:string prop ->
  ?button:
    value_elicitation_setting__prompt_specification__message_group__message__image_response_card__button
    list ->
  title:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__message__image_response_card

type value_elicitation_setting__prompt_specification__message_group__message__plain_text_message

val value_elicitation_setting__prompt_specification__message_group__message__plain_text_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__message__plain_text_message

type value_elicitation_setting__prompt_specification__message_group__message__ssml_message

val value_elicitation_setting__prompt_specification__message_group__message__ssml_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__message__ssml_message

type value_elicitation_setting__prompt_specification__message_group__message

val value_elicitation_setting__prompt_specification__message_group__message :
  ?custom_playload:
    value_elicitation_setting__prompt_specification__message_group__message__custom_playload
    list ->
  ?image_response_card:
    value_elicitation_setting__prompt_specification__message_group__message__image_response_card
    list ->
  ?plain_text_message:
    value_elicitation_setting__prompt_specification__message_group__message__plain_text_message
    list ->
  ?ssml_message:
    value_elicitation_setting__prompt_specification__message_group__message__ssml_message
    list ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__message

type value_elicitation_setting__prompt_specification__message_group__variation__custom_playload

val value_elicitation_setting__prompt_specification__message_group__variation__custom_playload :
  value:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__variation__custom_playload

type value_elicitation_setting__prompt_specification__message_group__variation__image_response_card__button

val value_elicitation_setting__prompt_specification__message_group__variation__image_response_card__button :
  text:string prop ->
  value:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__variation__image_response_card__button

type value_elicitation_setting__prompt_specification__message_group__variation__image_response_card

val value_elicitation_setting__prompt_specification__message_group__variation__image_response_card :
  ?image_url:string prop ->
  ?subtitle:string prop ->
  ?button:
    value_elicitation_setting__prompt_specification__message_group__variation__image_response_card__button
    list ->
  title:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__variation__image_response_card

type value_elicitation_setting__prompt_specification__message_group__variation__plain_text_message

val value_elicitation_setting__prompt_specification__message_group__variation__plain_text_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__variation__plain_text_message

type value_elicitation_setting__prompt_specification__message_group__variation__ssml_message

val value_elicitation_setting__prompt_specification__message_group__variation__ssml_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__variation__ssml_message

type value_elicitation_setting__prompt_specification__message_group__variation

val value_elicitation_setting__prompt_specification__message_group__variation :
  ?custom_playload:
    value_elicitation_setting__prompt_specification__message_group__variation__custom_playload
    list ->
  ?image_response_card:
    value_elicitation_setting__prompt_specification__message_group__variation__image_response_card
    list ->
  ?plain_text_message:
    value_elicitation_setting__prompt_specification__message_group__variation__plain_text_message
    list ->
  ?ssml_message:
    value_elicitation_setting__prompt_specification__message_group__variation__ssml_message
    list ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group__variation

type value_elicitation_setting__prompt_specification__message_group

val value_elicitation_setting__prompt_specification__message_group :
  ?message:
    value_elicitation_setting__prompt_specification__message_group__message
    list ->
  ?variation:
    value_elicitation_setting__prompt_specification__message_group__variation
    list ->
  unit ->
  value_elicitation_setting__prompt_specification__message_group

type value_elicitation_setting__prompt_specification__prompt_attempts_specification__allowed_input_types

val value_elicitation_setting__prompt_specification__prompt_attempts_specification__allowed_input_types :
  allow_audio_input:bool prop ->
  allow_dtmf_input:bool prop ->
  unit ->
  value_elicitation_setting__prompt_specification__prompt_attempts_specification__allowed_input_types

type value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification__audio_specification

val value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification__audio_specification :
  end_timeout_ms:float prop ->
  max_length_ms:float prop ->
  unit ->
  value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification__audio_specification

type value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification__dtmf_specification

val value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification__dtmf_specification :
  deletion_character:string prop ->
  end_character:string prop ->
  end_timeout_ms:float prop ->
  max_length:float prop ->
  unit ->
  value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification__dtmf_specification

type value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification

val value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification :
  ?audio_specification:
    value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification__audio_specification
    list ->
  ?dtmf_specification:
    value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification__dtmf_specification
    list ->
  start_timeout_ms:float prop ->
  unit ->
  value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification

type value_elicitation_setting__prompt_specification__prompt_attempts_specification__text_input_specification

val value_elicitation_setting__prompt_specification__prompt_attempts_specification__text_input_specification :
  start_timeout_ms:float prop ->
  unit ->
  value_elicitation_setting__prompt_specification__prompt_attempts_specification__text_input_specification

type value_elicitation_setting__prompt_specification__prompt_attempts_specification

val value_elicitation_setting__prompt_specification__prompt_attempts_specification :
  ?allow_interrupt:bool prop ->
  ?allowed_input_types:
    value_elicitation_setting__prompt_specification__prompt_attempts_specification__allowed_input_types
    list ->
  ?audio_and_dtmf_input_specification:
    value_elicitation_setting__prompt_specification__prompt_attempts_specification__audio_and_dtmf_input_specification
    list ->
  ?text_input_specification:
    value_elicitation_setting__prompt_specification__prompt_attempts_specification__text_input_specification
    list ->
  map_block_key:string prop ->
  unit ->
  value_elicitation_setting__prompt_specification__prompt_attempts_specification

type value_elicitation_setting__prompt_specification

val value_elicitation_setting__prompt_specification :
  ?allow_interrupt:bool prop ->
  ?message_selection_strategy:string prop ->
  ?message_group:
    value_elicitation_setting__prompt_specification__message_group
    list ->
  max_retries:float prop ->
  prompt_attempts_specification:
    value_elicitation_setting__prompt_specification__prompt_attempts_specification
    list ->
  unit ->
  value_elicitation_setting__prompt_specification

type value_elicitation_setting__sample_utterance

val value_elicitation_setting__sample_utterance :
  utterance:string prop ->
  unit ->
  value_elicitation_setting__sample_utterance

type value_elicitation_setting__slot_resolution_setting

val value_elicitation_setting__slot_resolution_setting :
  slot_resolution_strategy:string prop ->
  unit ->
  value_elicitation_setting__slot_resolution_setting

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__custom_playload

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__custom_playload :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__custom_playload

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__image_response_card__button

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__image_response_card__button :
  text:string prop ->
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__image_response_card__button

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__image_response_card

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__image_response_card :
  ?image_url:string prop ->
  ?subtitle:string prop ->
  ?button:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__image_response_card__button
    list ->
  title:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__image_response_card

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__plain_text_message

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__plain_text_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__plain_text_message

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__ssml_message

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__ssml_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__ssml_message

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message :
  ?custom_playload:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__custom_playload
    list ->
  ?image_response_card:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__image_response_card
    list ->
  ?plain_text_message:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__plain_text_message
    list ->
  ?ssml_message:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message__ssml_message
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__custom_playload

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__custom_playload :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__custom_playload

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__image_response_card__button

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__image_response_card__button :
  text:string prop ->
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__image_response_card__button

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__image_response_card

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__image_response_card :
  ?image_url:string prop ->
  ?subtitle:string prop ->
  ?button:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__image_response_card__button
    list ->
  title:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__image_response_card

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__plain_text_message

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__plain_text_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__plain_text_message

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__ssml_message

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__ssml_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__ssml_message

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation :
  ?custom_playload:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__custom_playload
    list ->
  ?image_response_card:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__image_response_card
    list ->
  ?plain_text_message:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__plain_text_message
    list ->
  ?ssml_message:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation__ssml_message
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation

type value_elicitation_setting__wait_and_continue_specification__continue_response__message_group

val value_elicitation_setting__wait_and_continue_specification__continue_response__message_group :
  ?message:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__message
    list ->
  ?variation:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group__variation
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response__message_group

type value_elicitation_setting__wait_and_continue_specification__continue_response

val value_elicitation_setting__wait_and_continue_specification__continue_response :
  ?allow_interrupt:bool prop ->
  ?message_group:
    value_elicitation_setting__wait_and_continue_specification__continue_response__message_group
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__continue_response

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__custom_playload

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__custom_playload :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__custom_playload

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__image_response_card__button

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__image_response_card__button :
  text:string prop ->
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__image_response_card__button

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__image_response_card

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__image_response_card :
  ?image_url:string prop ->
  ?subtitle:string prop ->
  ?button:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__image_response_card__button
    list ->
  title:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__image_response_card

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__plain_text_message

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__plain_text_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__plain_text_message

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__ssml_message

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__ssml_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__ssml_message

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message :
  ?custom_playload:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__custom_playload
    list ->
  ?image_response_card:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__image_response_card
    list ->
  ?plain_text_message:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__plain_text_message
    list ->
  ?ssml_message:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message__ssml_message
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__custom_playload

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__custom_playload :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__custom_playload

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__image_response_card__button

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__image_response_card__button :
  text:string prop ->
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__image_response_card__button

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__image_response_card

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__image_response_card :
  ?image_url:string prop ->
  ?subtitle:string prop ->
  ?button:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__image_response_card__button
    list ->
  title:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__image_response_card

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__plain_text_message

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__plain_text_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__plain_text_message

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__ssml_message

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__ssml_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__ssml_message

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation :
  ?custom_playload:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__custom_playload
    list ->
  ?image_response_card:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__image_response_card
    list ->
  ?plain_text_message:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__plain_text_message
    list ->
  ?ssml_message:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation__ssml_message
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group :
  ?message:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__message
    list ->
  ?variation:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group__variation
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group

type value_elicitation_setting__wait_and_continue_specification__still_waiting_response

val value_elicitation_setting__wait_and_continue_specification__still_waiting_response :
  ?allow_interrupt:bool prop ->
  ?message_group:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response__message_group
    list ->
  frequency_in_seconds:float prop ->
  timeout_in_seconds:float prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__still_waiting_response

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__custom_playload

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__custom_playload :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__custom_playload

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__image_response_card__button

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__image_response_card__button :
  text:string prop ->
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__image_response_card__button

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__image_response_card

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__image_response_card :
  ?image_url:string prop ->
  ?subtitle:string prop ->
  ?button:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__image_response_card__button
    list ->
  title:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__image_response_card

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__plain_text_message

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__plain_text_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__plain_text_message

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__ssml_message

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__ssml_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__ssml_message

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message :
  ?custom_playload:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__custom_playload
    list ->
  ?image_response_card:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__image_response_card
    list ->
  ?plain_text_message:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__plain_text_message
    list ->
  ?ssml_message:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message__ssml_message
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__custom_playload

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__custom_playload :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__custom_playload

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__image_response_card__button

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__image_response_card__button :
  text:string prop ->
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__image_response_card__button

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__image_response_card

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__image_response_card :
  ?image_url:string prop ->
  ?subtitle:string prop ->
  ?button:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__image_response_card__button
    list ->
  title:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__image_response_card

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__plain_text_message

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__plain_text_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__plain_text_message

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__ssml_message

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__ssml_message :
  value:string prop ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__ssml_message

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation :
  ?custom_playload:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__custom_playload
    list ->
  ?image_response_card:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__image_response_card
    list ->
  ?plain_text_message:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__plain_text_message
    list ->
  ?ssml_message:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation__ssml_message
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation

type value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group

val value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group :
  ?message:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__message
    list ->
  ?variation:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group__variation
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group

type value_elicitation_setting__wait_and_continue_specification__waiting_response

val value_elicitation_setting__wait_and_continue_specification__waiting_response :
  ?allow_interrupt:bool prop ->
  ?message_group:
    value_elicitation_setting__wait_and_continue_specification__waiting_response__message_group
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification__waiting_response

type value_elicitation_setting__wait_and_continue_specification

val value_elicitation_setting__wait_and_continue_specification :
  ?active:bool prop ->
  ?continue_response:
    value_elicitation_setting__wait_and_continue_specification__continue_response
    list ->
  ?still_waiting_response:
    value_elicitation_setting__wait_and_continue_specification__still_waiting_response
    list ->
  ?waiting_response:
    value_elicitation_setting__wait_and_continue_specification__waiting_response
    list ->
  unit ->
  value_elicitation_setting__wait_and_continue_specification

type value_elicitation_setting

val value_elicitation_setting :
  ?default_value_specification:
    value_elicitation_setting__default_value_specification list ->
  ?prompt_specification:
    value_elicitation_setting__prompt_specification list ->
  ?sample_utterance:value_elicitation_setting__sample_utterance list ->
  ?slot_resolution_setting:
    value_elicitation_setting__slot_resolution_setting list ->
  ?wait_and_continue_specification:
    value_elicitation_setting__wait_and_continue_specification list ->
  slot_constraint:string prop ->
  unit ->
  value_elicitation_setting

type aws_lexv2models_slot

val aws_lexv2models_slot :
  ?description:string prop ->
  ?slot_type_id:string prop ->
  ?multiple_values_setting:multiple_values_setting list ->
  ?obfuscation_setting:obfuscation_setting list ->
  ?timeouts:timeouts ->
  ?value_elicitation_setting:value_elicitation_setting list ->
  bot_id:string prop ->
  bot_version:string prop ->
  intent_id:string prop ->
  locale_id:string prop ->
  name:string prop ->
  unit ->
  aws_lexv2models_slot

val yojson_of_aws_lexv2models_slot : aws_lexv2models_slot -> json

(** RESOURCE REGISTRATION *)

type t = private {
  bot_id : string prop;
  bot_version : string prop;
  description : string prop;
  id : string prop;
  intent_id : string prop;
  locale_id : string prop;
  name : string prop;
  slot_id : string prop;
  slot_type_id : string prop;
}

val register :
  ?tf_module:tf_module ->
  ?description:string prop ->
  ?slot_type_id:string prop ->
  ?multiple_values_setting:multiple_values_setting list ->
  ?obfuscation_setting:obfuscation_setting list ->
  ?timeouts:timeouts ->
  ?value_elicitation_setting:value_elicitation_setting list ->
  bot_id:string prop ->
  bot_version:string prop ->
  intent_id:string prop ->
  locale_id:string prop ->
  name:string prop ->
  string ->
  t

val make :
  ?description:string prop ->
  ?slot_type_id:string prop ->
  ?multiple_values_setting:multiple_values_setting list ->
  ?obfuscation_setting:obfuscation_setting list ->
  ?timeouts:timeouts ->
  ?value_elicitation_setting:value_elicitation_setting list ->
  bot_id:string prop ->
  bot_version:string prop ->
  intent_id:string prop ->
  locale_id:string prop ->
  name:string prop ->
  string ->
  t Tf_core.resource
