(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration__security_control_custom_parameter__parameter__bool

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration__security_control_custom_parameter__parameter__double

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration__security_control_custom_parameter__parameter__enum

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration__security_control_custom_parameter__parameter__enum_list

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration__security_control_custom_parameter__parameter__int

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration__security_control_custom_parameter__parameter__int_list

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration__security_control_custom_parameter__parameter__string

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration__security_control_custom_parameter__parameter__string_list

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration__security_control_custom_parameter__parameter

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration__security_control_custom_parameter

type aws_securityhub_configuration_policy__configuration_policy__security_controls_configuration

type aws_securityhub_configuration_policy__configuration_policy
type aws_securityhub_configuration_policy

type t = private {
  arn : string prop;
  description : string prop;
  id : string prop;
  name : string prop;
}

val aws_securityhub_configuration_policy :
  ?description:string prop ->
  ?id:string prop ->
  name:string prop ->
  configuration_policy:
    aws_securityhub_configuration_policy__configuration_policy list ->
  string ->
  t
