(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type kubernetes_cron_job_v1__metadata
type kubernetes_cron_job_v1__spec__job_template__metadata

type kubernetes_cron_job_v1__spec__job_template__spec__pod_failure_policy__rule__on_exit_codes

type kubernetes_cron_job_v1__spec__job_template__spec__pod_failure_policy__rule__on_pod_condition

type kubernetes_cron_job_v1__spec__job_template__spec__pod_failure_policy__rule

type kubernetes_cron_job_v1__spec__job_template__spec__pod_failure_policy

type kubernetes_cron_job_v1__spec__job_template__spec__selector__match_expressions

type kubernetes_cron_job_v1__spec__job_template__spec__selector

type kubernetes_cron_job_v1__spec__job_template__spec__template__metadata

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__node_affinity__preferred_during_scheduling_ignored_during_execution__preference__match_expressions

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__node_affinity__preferred_during_scheduling_ignored_during_execution__preference__match_fields

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__node_affinity__preferred_during_scheduling_ignored_during_execution__preference

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__node_affinity__preferred_during_scheduling_ignored_during_execution

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__node_affinity__required_during_scheduling_ignored_during_execution__node_selector_term__match_expressions

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__node_affinity__required_during_scheduling_ignored_during_execution__node_selector_term__match_fields

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__node_affinity__required_during_scheduling_ignored_during_execution__node_selector_term

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__node_affinity__required_during_scheduling_ignored_during_execution

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__node_affinity

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_affinity__preferred_during_scheduling_ignored_during_execution__pod_affinity_term__label_selector__match_expressions

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_affinity__preferred_during_scheduling_ignored_during_execution__pod_affinity_term__label_selector

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_affinity__preferred_during_scheduling_ignored_during_execution__pod_affinity_term

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_affinity__preferred_during_scheduling_ignored_during_execution

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_affinity__required_during_scheduling_ignored_during_execution__label_selector__match_expressions

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_affinity__required_during_scheduling_ignored_during_execution__label_selector

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_affinity__required_during_scheduling_ignored_during_execution

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_affinity

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_anti_affinity__preferred_during_scheduling_ignored_during_execution__pod_affinity_term__label_selector__match_expressions

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_anti_affinity__preferred_during_scheduling_ignored_during_execution__pod_affinity_term__label_selector

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_anti_affinity__preferred_during_scheduling_ignored_during_execution__pod_affinity_term

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_anti_affinity__preferred_during_scheduling_ignored_during_execution

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_anti_affinity__required_during_scheduling_ignored_during_execution__label_selector__match_expressions

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_anti_affinity__required_during_scheduling_ignored_during_execution__label_selector

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_anti_affinity__required_during_scheduling_ignored_during_execution

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity__pod_anti_affinity

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__affinity

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__env__value_from__config_map_key_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__env__value_from__field_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__env__value_from__resource_field_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__env__value_from__secret_key_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__env__value_from

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__env

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__env_from__config_map_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__env_from__secret_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__env_from

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle__post_start__exec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle__post_start__http_get__http_header

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle__post_start__http_get

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle__post_start__tcp_socket

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle__post_start

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle__pre_stop__exec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle__pre_stop__http_get__http_header

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle__pre_stop__http_get

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle__pre_stop__tcp_socket

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle__pre_stop

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__lifecycle

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__liveness_probe__exec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__liveness_probe__grpc

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__liveness_probe__http_get__http_header

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__liveness_probe__http_get

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__liveness_probe__tcp_socket

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__liveness_probe

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__port

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__readiness_probe__exec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__readiness_probe__grpc

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__readiness_probe__http_get__http_header

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__readiness_probe__http_get

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__readiness_probe__tcp_socket

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__readiness_probe

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__resources

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__security_context__capabilities

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__security_context__se_linux_options

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__security_context__seccomp_profile

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__security_context

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__startup_probe__exec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__startup_probe__grpc

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__startup_probe__http_get__http_header

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__startup_probe__http_get

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__startup_probe__tcp_socket

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__startup_probe

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container__volume_mount

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__container

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__dns_config__option

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__dns_config

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__host_aliases

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__image_pull_secrets

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__env__value_from__config_map_key_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__env__value_from__field_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__env__value_from__resource_field_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__env__value_from__secret_key_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__env__value_from

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__env

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__env_from__config_map_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__env_from__secret_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__env_from

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle__post_start__exec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle__post_start__http_get__http_header

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle__post_start__http_get

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle__post_start__tcp_socket

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle__post_start

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle__pre_stop__exec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle__pre_stop__http_get__http_header

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle__pre_stop__http_get

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle__pre_stop__tcp_socket

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle__pre_stop

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__lifecycle

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__liveness_probe__exec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__liveness_probe__grpc

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__liveness_probe__http_get__http_header

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__liveness_probe__http_get

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__liveness_probe__tcp_socket

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__liveness_probe

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__port

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__readiness_probe__exec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__readiness_probe__grpc

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__readiness_probe__http_get__http_header

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__readiness_probe__http_get

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__readiness_probe__tcp_socket

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__readiness_probe

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__resources

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__security_context__capabilities

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__security_context__se_linux_options

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__security_context__seccomp_profile

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__security_context

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__startup_probe__exec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__startup_probe__grpc

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__startup_probe__http_get__http_header

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__startup_probe__http_get

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__startup_probe__tcp_socket

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__startup_probe

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container__volume_mount

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__init_container

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__os

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__readiness_gate

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__security_context__se_linux_options

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__security_context__seccomp_profile

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__security_context__sysctl

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__security_context__windows_options

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__security_context

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__toleration

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__topology_spread_constraint__label_selector__match_expressions

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__topology_spread_constraint__label_selector

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__topology_spread_constraint

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__aws_elastic_block_store

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__azure_disk

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__azure_file

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__ceph_fs__secret_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__ceph_fs

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__cinder

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__config_map__items

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__config_map

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__csi__node_publish_secret_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__csi

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__downward_api__items__field_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__downward_api__items__resource_field_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__downward_api__items

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__downward_api

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__empty_dir

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__ephemeral__volume_claim_template__metadata

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__ephemeral__volume_claim_template__spec__resources

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__ephemeral__volume_claim_template__spec__selector__match_expressions

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__ephemeral__volume_claim_template__spec__selector

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__ephemeral__volume_claim_template__spec

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__ephemeral__volume_claim_template

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__ephemeral

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__fc

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__flex_volume__secret_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__flex_volume

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__flocker

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__gce_persistent_disk

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__git_repo

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__glusterfs

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__host_path

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__iscsi

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__local

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__nfs

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__persistent_volume_claim

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__photon_persistent_disk

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected__sources__config_map__items

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected__sources__config_map

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected__sources__downward_api__items__field_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected__sources__downward_api__items__resource_field_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected__sources__downward_api__items

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected__sources__downward_api

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected__sources__secret__items

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected__sources__secret

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected__sources__service_account_token

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected__sources

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__projected

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__quobyte

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__rbd__secret_ref

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__rbd

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__secret__items

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__secret

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume__vsphere_volume

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec__volume

type kubernetes_cron_job_v1__spec__job_template__spec__template__spec
type kubernetes_cron_job_v1__spec__job_template__spec__template
type kubernetes_cron_job_v1__spec__job_template__spec
type kubernetes_cron_job_v1__spec__job_template
type kubernetes_cron_job_v1__spec
type kubernetes_cron_job_v1__timeouts
type kubernetes_cron_job_v1

val kubernetes_cron_job_v1 :
  ?id:string ->
  ?timeouts:kubernetes_cron_job_v1__timeouts ->
  metadata:kubernetes_cron_job_v1__metadata list ->
  spec:kubernetes_cron_job_v1__spec list ->
  string ->
  unit
