(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type kubernetes_horizontal_pod_autoscaler_v2__metadata

type kubernetes_horizontal_pod_autoscaler_v2__spec__behavior__scale_down__policy

type kubernetes_horizontal_pod_autoscaler_v2__spec__behavior__scale_down

type kubernetes_horizontal_pod_autoscaler_v2__spec__behavior__scale_up__policy

type kubernetes_horizontal_pod_autoscaler_v2__spec__behavior__scale_up
type kubernetes_horizontal_pod_autoscaler_v2__spec__behavior

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__container_resource__target

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__container_resource

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__external__metric__selector__match_expressions

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__external__metric__selector

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__external__metric

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__external__target

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__external

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__object__described_object

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__object__metric__selector__match_expressions

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__object__metric__selector

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__object__metric

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__object__target

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__object

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__pods__metric__selector__match_expressions

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__pods__metric__selector

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__pods__metric

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__pods__target

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__pods

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__resource__target

type kubernetes_horizontal_pod_autoscaler_v2__spec__metric__resource
type kubernetes_horizontal_pod_autoscaler_v2__spec__metric
type kubernetes_horizontal_pod_autoscaler_v2__spec__scale_target_ref
type kubernetes_horizontal_pod_autoscaler_v2__spec
type kubernetes_horizontal_pod_autoscaler_v2

val kubernetes_horizontal_pod_autoscaler_v2 :
  metadata:kubernetes_horizontal_pod_autoscaler_v2__metadata list ->
  spec:kubernetes_horizontal_pod_autoscaler_v2__spec list ->
  string ->
  unit
