(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type kubernetes_network_policy_v1__metadata
type kubernetes_network_policy_v1__spec__egress__ports
type kubernetes_network_policy_v1__spec__egress__to__ip_block

type kubernetes_network_policy_v1__spec__egress__to__namespace_selector__match_expressions

type kubernetes_network_policy_v1__spec__egress__to__namespace_selector

type kubernetes_network_policy_v1__spec__egress__to__pod_selector__match_expressions

type kubernetes_network_policy_v1__spec__egress__to__pod_selector
type kubernetes_network_policy_v1__spec__egress__to
type kubernetes_network_policy_v1__spec__egress
type kubernetes_network_policy_v1__spec__ingress__from__ip_block

type kubernetes_network_policy_v1__spec__ingress__from__namespace_selector__match_expressions

type kubernetes_network_policy_v1__spec__ingress__from__namespace_selector

type kubernetes_network_policy_v1__spec__ingress__from__pod_selector__match_expressions

type kubernetes_network_policy_v1__spec__ingress__from__pod_selector
type kubernetes_network_policy_v1__spec__ingress__from
type kubernetes_network_policy_v1__spec__ingress__ports
type kubernetes_network_policy_v1__spec__ingress

type kubernetes_network_policy_v1__spec__pod_selector__match_expressions

type kubernetes_network_policy_v1__spec__pod_selector
type kubernetes_network_policy_v1__spec
type kubernetes_network_policy_v1

val kubernetes_network_policy_v1 :
  metadata:kubernetes_network_policy_v1__metadata list ->
  spec:kubernetes_network_policy_v1__spec list ->
  string ->
  unit
