(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type kubernetes_persistent_volume__metadata
type kubernetes_persistent_volume__spec__claim_ref

type kubernetes_persistent_volume__spec__node_affinity__required__node_selector_term__match_expressions

type kubernetes_persistent_volume__spec__node_affinity__required__node_selector_term__match_fields

type kubernetes_persistent_volume__spec__node_affinity__required__node_selector_term

type kubernetes_persistent_volume__spec__node_affinity__required
type kubernetes_persistent_volume__spec__node_affinity

type kubernetes_persistent_volume__spec__persistent_volume_source__aws_elastic_block_store

type kubernetes_persistent_volume__spec__persistent_volume_source__azure_disk

type kubernetes_persistent_volume__spec__persistent_volume_source__azure_file

type kubernetes_persistent_volume__spec__persistent_volume_source__ceph_fs__secret_ref

type kubernetes_persistent_volume__spec__persistent_volume_source__ceph_fs

type kubernetes_persistent_volume__spec__persistent_volume_source__cinder

type kubernetes_persistent_volume__spec__persistent_volume_source__csi__controller_expand_secret_ref

type kubernetes_persistent_volume__spec__persistent_volume_source__csi__controller_publish_secret_ref

type kubernetes_persistent_volume__spec__persistent_volume_source__csi__node_publish_secret_ref

type kubernetes_persistent_volume__spec__persistent_volume_source__csi__node_stage_secret_ref

type kubernetes_persistent_volume__spec__persistent_volume_source__csi
type kubernetes_persistent_volume__spec__persistent_volume_source__fc

type kubernetes_persistent_volume__spec__persistent_volume_source__flex_volume__secret_ref

type kubernetes_persistent_volume__spec__persistent_volume_source__flex_volume

type kubernetes_persistent_volume__spec__persistent_volume_source__flocker

type kubernetes_persistent_volume__spec__persistent_volume_source__gce_persistent_disk

type kubernetes_persistent_volume__spec__persistent_volume_source__glusterfs

type kubernetes_persistent_volume__spec__persistent_volume_source__host_path

type kubernetes_persistent_volume__spec__persistent_volume_source__iscsi

type kubernetes_persistent_volume__spec__persistent_volume_source__local

type kubernetes_persistent_volume__spec__persistent_volume_source__nfs

type kubernetes_persistent_volume__spec__persistent_volume_source__photon_persistent_disk

type kubernetes_persistent_volume__spec__persistent_volume_source__quobyte

type kubernetes_persistent_volume__spec__persistent_volume_source__rbd__secret_ref

type kubernetes_persistent_volume__spec__persistent_volume_source__rbd

type kubernetes_persistent_volume__spec__persistent_volume_source__vsphere_volume

type kubernetes_persistent_volume__spec__persistent_volume_source
type kubernetes_persistent_volume__spec
type kubernetes_persistent_volume__timeouts
type kubernetes_persistent_volume

val kubernetes_persistent_volume :
  ?timeouts:kubernetes_persistent_volume__timeouts ->
  metadata:kubernetes_persistent_volume__metadata list ->
  spec:kubernetes_persistent_volume__spec list ->
  string ->
  unit
