(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_data_loss_prevention_inspect_template__inspect_config__custom_info_types__dictionary__cloud_storage_path

type google_data_loss_prevention_inspect_template__inspect_config__custom_info_types__dictionary__word_list

type google_data_loss_prevention_inspect_template__inspect_config__custom_info_types__dictionary

type google_data_loss_prevention_inspect_template__inspect_config__custom_info_types__info_type__sensitivity_score

type google_data_loss_prevention_inspect_template__inspect_config__custom_info_types__info_type

type google_data_loss_prevention_inspect_template__inspect_config__custom_info_types__regex

type google_data_loss_prevention_inspect_template__inspect_config__custom_info_types__sensitivity_score

type google_data_loss_prevention_inspect_template__inspect_config__custom_info_types__stored_type

type google_data_loss_prevention_inspect_template__inspect_config__custom_info_types__surrogate_type

type google_data_loss_prevention_inspect_template__inspect_config__custom_info_types

type google_data_loss_prevention_inspect_template__inspect_config__info_types__sensitivity_score

type google_data_loss_prevention_inspect_template__inspect_config__info_types

type google_data_loss_prevention_inspect_template__inspect_config__limits__max_findings_per_info_type__info_type__sensitivity_score

type google_data_loss_prevention_inspect_template__inspect_config__limits__max_findings_per_info_type__info_type

type google_data_loss_prevention_inspect_template__inspect_config__limits__max_findings_per_info_type

type google_data_loss_prevention_inspect_template__inspect_config__limits

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__info_types__sensitivity_score

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__info_types

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule__dictionary__cloud_storage_path

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule__dictionary__word_list

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule__dictionary

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule__exclude_by_hotword__hotword_regex

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule__exclude_by_hotword__proximity

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule__exclude_by_hotword

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule__exclude_info_types__info_types__sensitivity_score

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule__exclude_info_types__info_types

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule__exclude_info_types

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule__regex

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__exclusion_rule

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__hotword_rule__hotword_regex

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__hotword_rule__likelihood_adjustment

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__hotword_rule__proximity

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules__hotword_rule

type google_data_loss_prevention_inspect_template__inspect_config__rule_set__rules

type google_data_loss_prevention_inspect_template__inspect_config__rule_set

type google_data_loss_prevention_inspect_template__inspect_config
type google_data_loss_prevention_inspect_template__timeouts
type google_data_loss_prevention_inspect_template

val google_data_loss_prevention_inspect_template :
  ?description:string prop ->
  ?display_name:string prop ->
  ?id:string prop ->
  ?template_id:string prop ->
  ?timeouts:google_data_loss_prevention_inspect_template__timeouts ->
  parent:string prop ->
  inspect_config:
    google_data_loss_prevention_inspect_template__inspect_config list ->
  string ->
  unit
