(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_document_ai_warehouse_document_schema__property_definitions__date_time_type_options

type google_document_ai_warehouse_document_schema__property_definitions__enum_type_options

type google_document_ai_warehouse_document_schema__property_definitions__float_type_options

type google_document_ai_warehouse_document_schema__property_definitions__integer_type_options

type google_document_ai_warehouse_document_schema__property_definitions__map_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__date_time_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__enum_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__float_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__integer_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__map_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__schema_sources

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__text_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions__timestamp_type_options

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options__property_definitions

type google_document_ai_warehouse_document_schema__property_definitions__property_type_options

type google_document_ai_warehouse_document_schema__property_definitions__schema_sources

type google_document_ai_warehouse_document_schema__property_definitions__text_type_options

type google_document_ai_warehouse_document_schema__property_definitions__timestamp_type_options

type google_document_ai_warehouse_document_schema__property_definitions

type google_document_ai_warehouse_document_schema__timeouts
type google_document_ai_warehouse_document_schema

val google_document_ai_warehouse_document_schema :
  ?document_is_folder:bool ->
  ?id:string ->
  ?timeouts:google_document_ai_warehouse_document_schema__timeouts ->
  display_name:string ->
  location:string ->
  project_number:string ->
  property_definitions:
    google_document_ai_warehouse_document_schema__property_definitions
    list ->
  string ->
  unit
