(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_data_loss_prevention_job_trigger__inspect_job__actions__deidentify__transformation_config

type google_data_loss_prevention_job_trigger__inspect_job__actions__deidentify__transformation_details_storage_config__table

type google_data_loss_prevention_job_trigger__inspect_job__actions__deidentify__transformation_details_storage_config

type google_data_loss_prevention_job_trigger__inspect_job__actions__deidentify

type google_data_loss_prevention_job_trigger__inspect_job__actions__job_notification_emails

type google_data_loss_prevention_job_trigger__inspect_job__actions__pub_sub

type google_data_loss_prevention_job_trigger__inspect_job__actions__publish_findings_to_cloud_data_catalog

type google_data_loss_prevention_job_trigger__inspect_job__actions__publish_summary_to_cscc

type google_data_loss_prevention_job_trigger__inspect_job__actions__publish_to_stackdriver

type google_data_loss_prevention_job_trigger__inspect_job__actions__save_findings__output_config__table

type google_data_loss_prevention_job_trigger__inspect_job__actions__save_findings__output_config

type google_data_loss_prevention_job_trigger__inspect_job__actions__save_findings

type google_data_loss_prevention_job_trigger__inspect_job__actions

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__custom_info_types__dictionary__cloud_storage_path

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__custom_info_types__dictionary__word_list

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__custom_info_types__dictionary

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__custom_info_types__info_type__sensitivity_score

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__custom_info_types__info_type

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__custom_info_types__regex

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__custom_info_types__sensitivity_score

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__custom_info_types__stored_type

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__custom_info_types__surrogate_type

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__custom_info_types

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__info_types__sensitivity_score

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__info_types

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__limits__max_findings_per_info_type__info_type__sensitivity_score

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__limits__max_findings_per_info_type__info_type

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__limits__max_findings_per_info_type

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__limits

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__info_types__sensitivity_score

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__info_types

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule__dictionary__cloud_storage_path

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule__dictionary__word_list

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule__dictionary

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule__exclude_by_hotword__hotword_regex

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule__exclude_by_hotword__proximity

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule__exclude_by_hotword

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule__exclude_info_types__info_types__sensitivity_score

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule__exclude_info_types__info_types

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule__exclude_info_types

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule__regex

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__exclusion_rule

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__hotword_rule__hotword_regex

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__hotword_rule__likelihood_adjustment

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__hotword_rule__proximity

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules__hotword_rule

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set__rules

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config__rule_set

type google_data_loss_prevention_job_trigger__inspect_job__inspect_config

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__big_query_options__excluded_fields

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__big_query_options__identifying_fields

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__big_query_options__included_fields

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__big_query_options__table_reference

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__big_query_options

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__cloud_storage_options__file_set__regex_file_set

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__cloud_storage_options__file_set

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__cloud_storage_options

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__datastore_options__kind

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__datastore_options__partition_id

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__datastore_options

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__hybrid_options__table_options__identifying_fields

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__hybrid_options__table_options

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__hybrid_options

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__timespan_config__timestamp_field

type google_data_loss_prevention_job_trigger__inspect_job__storage_config__timespan_config

type google_data_loss_prevention_job_trigger__inspect_job__storage_config

type google_data_loss_prevention_job_trigger__inspect_job
type google_data_loss_prevention_job_trigger__timeouts
type google_data_loss_prevention_job_trigger__triggers__manual
type google_data_loss_prevention_job_trigger__triggers__schedule
type google_data_loss_prevention_job_trigger__triggers
type google_data_loss_prevention_job_trigger

val google_data_loss_prevention_job_trigger :
  ?description:string ->
  ?display_name:string ->
  ?status:string ->
  ?timeouts:google_data_loss_prevention_job_trigger__timeouts ->
  parent:string ->
  inspect_job:
    google_data_loss_prevention_job_trigger__inspect_job list ->
  triggers:google_data_loss_prevention_job_trigger__triggers list ->
  string ->
  unit
