(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_access_context_manager_service_perimeters__service_perimeters__spec__egress_policies__egress_from__sources

type google_access_context_manager_service_perimeters__service_perimeters__spec__egress_policies__egress_from

type google_access_context_manager_service_perimeters__service_perimeters__spec__egress_policies__egress_to__operations__method_selectors

type google_access_context_manager_service_perimeters__service_perimeters__spec__egress_policies__egress_to__operations

type google_access_context_manager_service_perimeters__service_perimeters__spec__egress_policies__egress_to

type google_access_context_manager_service_perimeters__service_perimeters__spec__egress_policies

type google_access_context_manager_service_perimeters__service_perimeters__spec__ingress_policies__ingress_from__sources

type google_access_context_manager_service_perimeters__service_perimeters__spec__ingress_policies__ingress_from

type google_access_context_manager_service_perimeters__service_perimeters__spec__ingress_policies__ingress_to__operations__method_selectors

type google_access_context_manager_service_perimeters__service_perimeters__spec__ingress_policies__ingress_to__operations

type google_access_context_manager_service_perimeters__service_perimeters__spec__ingress_policies__ingress_to

type google_access_context_manager_service_perimeters__service_perimeters__spec__ingress_policies

type google_access_context_manager_service_perimeters__service_perimeters__spec__vpc_accessible_services

type google_access_context_manager_service_perimeters__service_perimeters__spec

type google_access_context_manager_service_perimeters__service_perimeters__status__egress_policies__egress_from__sources

type google_access_context_manager_service_perimeters__service_perimeters__status__egress_policies__egress_from

type google_access_context_manager_service_perimeters__service_perimeters__status__egress_policies__egress_to__operations__method_selectors

type google_access_context_manager_service_perimeters__service_perimeters__status__egress_policies__egress_to__operations

type google_access_context_manager_service_perimeters__service_perimeters__status__egress_policies__egress_to

type google_access_context_manager_service_perimeters__service_perimeters__status__egress_policies

type google_access_context_manager_service_perimeters__service_perimeters__status__ingress_policies__ingress_from__sources

type google_access_context_manager_service_perimeters__service_perimeters__status__ingress_policies__ingress_from

type google_access_context_manager_service_perimeters__service_perimeters__status__ingress_policies__ingress_to__operations__method_selectors

type google_access_context_manager_service_perimeters__service_perimeters__status__ingress_policies__ingress_to__operations

type google_access_context_manager_service_perimeters__service_perimeters__status__ingress_policies__ingress_to

type google_access_context_manager_service_perimeters__service_perimeters__status__ingress_policies

type google_access_context_manager_service_perimeters__service_perimeters__status__vpc_accessible_services

type google_access_context_manager_service_perimeters__service_perimeters__status

type google_access_context_manager_service_perimeters__service_perimeters

type google_access_context_manager_service_perimeters__timeouts
type google_access_context_manager_service_perimeters

val google_access_context_manager_service_perimeters :
  ?timeouts:
    google_access_context_manager_service_perimeters__timeouts ->
  parent:string ->
  service_perimeters:
    google_access_context_manager_service_perimeters__service_perimeters
    list ->
  string ->
  unit
