(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_os_config_os_policy_assignment__instance_filter__exclusion_labels

type google_os_config_os_policy_assignment__instance_filter__inclusion_labels

type google_os_config_os_policy_assignment__instance_filter__inventories

type google_os_config_os_policy_assignment__instance_filter

type google_os_config_os_policy_assignment__os_policies__resource_groups__inventory_filters

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__exec__enforce__file__gcs

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__exec__enforce__file__remote

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__exec__enforce__file

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__exec__enforce

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__exec__validate__file__gcs

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__exec__validate__file__remote

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__exec__validate__file

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__exec__validate

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__exec

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__file__file__gcs

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__file__file__remote

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__file__file

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__file

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__apt

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__deb__source__gcs

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__deb__source__remote

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__deb__source

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__deb

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__googet

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__msi__source__gcs

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__msi__source__remote

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__msi__source

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__msi

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__rpm__source__gcs

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__rpm__source__remote

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__rpm__source

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__rpm

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__yum

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg__zypper

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__pkg

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__repository__apt

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__repository__goo

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__repository__yum

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__repository__zypper

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources__repository

type google_os_config_os_policy_assignment__os_policies__resource_groups__resources

type google_os_config_os_policy_assignment__os_policies__resource_groups

type google_os_config_os_policy_assignment__os_policies
type google_os_config_os_policy_assignment__rollout__disruption_budget
type google_os_config_os_policy_assignment__rollout
type google_os_config_os_policy_assignment__timeouts
type google_os_config_os_policy_assignment

type t = private {
  baseline : bool prop;
  deleted : bool prop;
  description : string prop;
  etag : string prop;
  id : string prop;
  location : string prop;
  name : string prop;
  project : string prop;
  reconciling : bool prop;
  revision_create_time : string prop;
  revision_id : string prop;
  rollout_state : string prop;
  skip_await_rollout : bool prop;
  uid : string prop;
}

val google_os_config_os_policy_assignment :
  ?description:string prop ->
  ?id:string prop ->
  ?project:string prop ->
  ?skip_await_rollout:bool prop ->
  ?timeouts:google_os_config_os_policy_assignment__timeouts ->
  location:string prop ->
  name:string prop ->
  instance_filter:
    google_os_config_os_policy_assignment__instance_filter list ->
  os_policies:google_os_config_os_policy_assignment__os_policies list ->
  rollout:google_os_config_os_policy_assignment__rollout list ->
  string ->
  t
