(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_dialogflow_cx_page__advanced_settings__dtmf_settings
type google_dialogflow_cx_page__advanced_settings
type google_dialogflow_cx_page__entry_fulfillment__conditional_cases

type google_dialogflow_cx_page__entry_fulfillment__messages__conversation_success

type google_dialogflow_cx_page__entry_fulfillment__messages__live_agent_handoff

type google_dialogflow_cx_page__entry_fulfillment__messages__output_audio_text

type google_dialogflow_cx_page__entry_fulfillment__messages__play_audio

type google_dialogflow_cx_page__entry_fulfillment__messages__telephony_transfer_call

type google_dialogflow_cx_page__entry_fulfillment__messages__text
type google_dialogflow_cx_page__entry_fulfillment__messages

type google_dialogflow_cx_page__entry_fulfillment__set_parameter_actions

type google_dialogflow_cx_page__entry_fulfillment

type google_dialogflow_cx_page__event_handlers__trigger_fulfillment__conditional_cases

type google_dialogflow_cx_page__event_handlers__trigger_fulfillment__messages__conversation_success

type google_dialogflow_cx_page__event_handlers__trigger_fulfillment__messages__live_agent_handoff

type google_dialogflow_cx_page__event_handlers__trigger_fulfillment__messages__output_audio_text

type google_dialogflow_cx_page__event_handlers__trigger_fulfillment__messages__play_audio

type google_dialogflow_cx_page__event_handlers__trigger_fulfillment__messages__telephony_transfer_call

type google_dialogflow_cx_page__event_handlers__trigger_fulfillment__messages__text

type google_dialogflow_cx_page__event_handlers__trigger_fulfillment__messages

type google_dialogflow_cx_page__event_handlers__trigger_fulfillment__set_parameter_actions

type google_dialogflow_cx_page__event_handlers__trigger_fulfillment
type google_dialogflow_cx_page__event_handlers

type google_dialogflow_cx_page__form__parameters__advanced_settings__dtmf_settings

type google_dialogflow_cx_page__form__parameters__advanced_settings

type google_dialogflow_cx_page__form__parameters__fill_behavior__initial_prompt_fulfillment__conditional_cases

type google_dialogflow_cx_page__form__parameters__fill_behavior__initial_prompt_fulfillment__messages__conversation_success

type google_dialogflow_cx_page__form__parameters__fill_behavior__initial_prompt_fulfillment__messages__live_agent_handoff

type google_dialogflow_cx_page__form__parameters__fill_behavior__initial_prompt_fulfillment__messages__output_audio_text

type google_dialogflow_cx_page__form__parameters__fill_behavior__initial_prompt_fulfillment__messages__play_audio

type google_dialogflow_cx_page__form__parameters__fill_behavior__initial_prompt_fulfillment__messages__telephony_transfer_call

type google_dialogflow_cx_page__form__parameters__fill_behavior__initial_prompt_fulfillment__messages__text

type google_dialogflow_cx_page__form__parameters__fill_behavior__initial_prompt_fulfillment__messages

type google_dialogflow_cx_page__form__parameters__fill_behavior__initial_prompt_fulfillment__set_parameter_actions

type google_dialogflow_cx_page__form__parameters__fill_behavior__initial_prompt_fulfillment

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers__trigger_fulfillment__conditional_cases

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers__trigger_fulfillment__messages__conversation_success

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers__trigger_fulfillment__messages__live_agent_handoff

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers__trigger_fulfillment__messages__output_audio_text

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers__trigger_fulfillment__messages__play_audio

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers__trigger_fulfillment__messages__telephony_transfer_call

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers__trigger_fulfillment__messages__text

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers__trigger_fulfillment__messages

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers__trigger_fulfillment__set_parameter_actions

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers__trigger_fulfillment

type google_dialogflow_cx_page__form__parameters__fill_behavior__reprompt_event_handlers

type google_dialogflow_cx_page__form__parameters__fill_behavior
type google_dialogflow_cx_page__form__parameters
type google_dialogflow_cx_page__form
type google_dialogflow_cx_page__timeouts

type google_dialogflow_cx_page__transition_routes__trigger_fulfillment__conditional_cases

type google_dialogflow_cx_page__transition_routes__trigger_fulfillment__messages__conversation_success

type google_dialogflow_cx_page__transition_routes__trigger_fulfillment__messages__live_agent_handoff

type google_dialogflow_cx_page__transition_routes__trigger_fulfillment__messages__output_audio_text

type google_dialogflow_cx_page__transition_routes__trigger_fulfillment__messages__play_audio

type google_dialogflow_cx_page__transition_routes__trigger_fulfillment__messages__telephony_transfer_call

type google_dialogflow_cx_page__transition_routes__trigger_fulfillment__messages__text

type google_dialogflow_cx_page__transition_routes__trigger_fulfillment__messages

type google_dialogflow_cx_page__transition_routes__trigger_fulfillment__set_parameter_actions

type google_dialogflow_cx_page__transition_routes__trigger_fulfillment
type google_dialogflow_cx_page__transition_routes
type google_dialogflow_cx_page

val google_dialogflow_cx_page :
  ?language_code:string ->
  ?parent:string ->
  ?transition_route_groups:string list ->
  ?timeouts:google_dialogflow_cx_page__timeouts ->
  display_name:string ->
  advanced_settings:google_dialogflow_cx_page__advanced_settings list ->
  entry_fulfillment:google_dialogflow_cx_page__entry_fulfillment list ->
  event_handlers:google_dialogflow_cx_page__event_handlers list ->
  form:google_dialogflow_cx_page__form list ->
  transition_routes:google_dialogflow_cx_page__transition_routes list ->
  string ->
  unit
