(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

[@@@ocaml.warning "-33-27-26"]

open! Tf.Prelude

type google_scc_project_custom_module__custom_config__custom_output__properties__value_expression = {
  description : string prop option; [@option]
      (** Description of the expression. This is a longer text which describes the
expression, e.g. when hovered over it in a UI. *)
  expression : string prop;
      (** Textual representation of an expression in Common Expression Language syntax. *)
  location : string prop option; [@option]
      (** String indicating the location of the expression for error reporting, e.g. a
file name and a position in the file. *)
  title : string prop option; [@option]
      (** Title for the expression, i.e. a short string describing its purpose. This can
be used e.g. in UIs which allow to enter the expression. *)
}
[@@deriving yojson_of]
(** The CEL expression for the custom output. A resource property can be specified
to return the value of the property or a text string enclosed in quotation marks. *)

type google_scc_project_custom_module__custom_config__custom_output__properties = {
  name : string prop option; [@option]
      (** Name of the property for the custom output. *)
  value_expression :
    google_scc_project_custom_module__custom_config__custom_output__properties__value_expression
    list;
}
[@@deriving yojson_of]
(** A list of custom output properties to add to the finding. *)

type google_scc_project_custom_module__custom_config__custom_output = {
  properties :
    google_scc_project_custom_module__custom_config__custom_output__properties
    list;
}
[@@deriving yojson_of]
(** Custom output properties. *)

type google_scc_project_custom_module__custom_config__predicate = {
  description : string prop option; [@option]
      (** Description of the expression. This is a longer text which describes the
expression, e.g. when hovered over it in a UI. *)
  expression : string prop;
      (** Textual representation of an expression in Common Expression Language syntax. *)
  location : string prop option; [@option]
      (** String indicating the location of the expression for error reporting, e.g. a
file name and a position in the file. *)
  title : string prop option; [@option]
      (** Title for the expression, i.e. a short string describing its purpose. This can
be used e.g. in UIs which allow to enter the expression. *)
}
[@@deriving yojson_of]
(** The CEL expression to evaluate to produce findings. When the expression evaluates
to true against a resource, a finding is generated. *)

type google_scc_project_custom_module__custom_config__resource_selector = {
  resource_types : string prop list;
      (** The resource types to run the detector on. *)
}
[@@deriving yojson_of]
(** The resource types that the custom module operates on. Each custom module
can specify up to 5 resource types. *)

type google_scc_project_custom_module__custom_config = {
  description : string prop option; [@option]
      (** Text that describes the vulnerability or misconfiguration that the custom
module detects. This explanation is returned with each finding instance to
help investigators understand the detected issue. The text must be enclosed in quotation marks. *)
  recommendation : string prop;
      (** An explanation of the recommended steps that security teams can take to resolve
the detected issue. This explanation is returned with each finding generated by
this module in the nextSteps property of the finding JSON. *)
  severity : string prop;
      (** The severity to assign to findings generated by the module. Possible values: [CRITICAL, HIGH, MEDIUM, LOW] *)
  custom_output :
    google_scc_project_custom_module__custom_config__custom_output
    list;
  predicate :
    google_scc_project_custom_module__custom_config__predicate list;
  resource_selector :
    google_scc_project_custom_module__custom_config__resource_selector
    list;
}
[@@deriving yojson_of]
(** The user specified custom configuration for the module. *)

type google_scc_project_custom_module__timeouts = {
  create : string prop option; [@option]  (** create *)
  delete : string prop option; [@option]  (** delete *)
  update : string prop option; [@option]  (** update *)
}
[@@deriving yojson_of]
(** google_scc_project_custom_module__timeouts *)

type google_scc_project_custom_module = {
  display_name : string prop;
      (** The display name of the Security Health Analytics custom module. This
display name becomes the finding category for all findings that are
returned by this custom module. The display name must be between 1 and
128 characters, start with a lowercase letter, and contain alphanumeric
characters or underscores only. *)
  enablement_state : string prop;
      (** The enablement state of the custom module. Possible values: [ENABLED, DISABLED] *)
  id : string prop option; [@option]  (** id *)
  project : string prop option; [@option]  (** project *)
  custom_config :
    google_scc_project_custom_module__custom_config list;
  timeouts : google_scc_project_custom_module__timeouts option;
}
[@@deriving yojson_of]
(** google_scc_project_custom_module *)

let google_scc_project_custom_module ?id ?project ?timeouts
    ~display_name ~enablement_state ~custom_config __resource_id =
  let __resource_type = "google_scc_project_custom_module" in
  let __resource =
    {
      display_name;
      enablement_state;
      id;
      project;
      custom_config;
      timeouts;
    }
  in
  Resource.add ~type_:__resource_type ~id:__resource_id
    (yojson_of_google_scc_project_custom_module __resource);
  ()
