(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_data_loss_prevention_deidentify_template__deidentify_config__image_transformations__transforms__all_info_types

type google_data_loss_prevention_deidentify_template__deidentify_config__image_transformations__transforms__all_text

type google_data_loss_prevention_deidentify_template__deidentify_config__image_transformations__transforms__redaction_color

type google_data_loss_prevention_deidentify_template__deidentify_config__image_transformations__transforms__selected_info_types__info_types__sensitivity_score

type google_data_loss_prevention_deidentify_template__deidentify_config__image_transformations__transforms__selected_info_types__info_types

type google_data_loss_prevention_deidentify_template__deidentify_config__image_transformations__transforms__selected_info_types

type google_data_loss_prevention_deidentify_template__deidentify_config__image_transformations__transforms

type google_data_loss_prevention_deidentify_template__deidentify_config__image_transformations

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__info_types__sensitivity_score

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__info_types

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__max__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__max__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__max

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__min__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__min__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__min

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__replacement_value__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__replacement_value__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__replacement_value

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__bucketing_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__character_mask_config__characters_to_ignore

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__character_mask_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__context

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__surrogate_info_type__sensitivity_score

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__surrogate_info_type

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_hash_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_hash_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_hash_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_hash_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_hash_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__context

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__surrogate_info_type__sensitivity_score

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__surrogate_info_type

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__date_shift_config__context

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__date_shift_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__date_shift_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__date_shift_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__date_shift_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__date_shift_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__fixed_size_bucketing_config__lower_bound

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__fixed_size_bucketing_config__upper_bound

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__fixed_size_bucketing_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__redact_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__replace_config__new_value__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__replace_config__new_value__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__replace_config__new_value

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__replace_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__replace_dictionary_config__word_list

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__replace_dictionary_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation__time_part_config

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations__primitive_transformation

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations__transformations

type google_data_loss_prevention_deidentify_template__deidentify_config__info_type_transformations

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__condition__expressions__conditions__conditions__field

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__condition__expressions__conditions__conditions__value__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__condition__expressions__conditions__conditions__value__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__condition__expressions__conditions__conditions__value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__condition__expressions__conditions__conditions

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__condition__expressions__conditions

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__condition__expressions

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__condition

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__fields

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__info_types__sensitivity_score

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__info_types

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__max__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__max__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__max

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__min__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__min__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__min

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__replacement_value__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__replacement_value__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets__replacement_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config__buckets

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__bucketing_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__character_mask_config__characters_to_ignore

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__character_mask_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__context

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__surrogate_info_type__sensitivity_score

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config__surrogate_info_type

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_deterministic_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_hash_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_hash_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_hash_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_hash_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_hash_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__context

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__surrogate_info_type__sensitivity_score

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config__surrogate_info_type

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__crypto_replace_ffx_fpe_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__date_shift_config__context

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__date_shift_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__date_shift_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__date_shift_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__date_shift_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__date_shift_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__fixed_size_bucketing_config__lower_bound

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__fixed_size_bucketing_config__upper_bound

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__fixed_size_bucketing_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__redact_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__replace_config__new_value__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__replace_config__new_value__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__replace_config__new_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__replace_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__replace_dictionary_config__word_list

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__replace_dictionary_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__replace_with_info_type_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation__time_part_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations__primitive_transformation

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations__transformations

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__info_type_transformations

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config__buckets__max__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config__buckets__max__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config__buckets__max

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config__buckets__min__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config__buckets__min__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config__buckets__min

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config__buckets__replacement_value__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config__buckets__replacement_value__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config__buckets__replacement_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config__buckets

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__bucketing_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__character_mask_config__characters_to_ignore

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__character_mask_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_deterministic_config__context

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_deterministic_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_deterministic_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_deterministic_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_deterministic_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_deterministic_config__surrogate_info_type__sensitivity_score

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_deterministic_config__surrogate_info_type

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_deterministic_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_hash_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_hash_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_hash_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_hash_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_hash_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_replace_ffx_fpe_config__context

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_replace_ffx_fpe_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_replace_ffx_fpe_config__surrogate_info_type__sensitivity_score

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_replace_ffx_fpe_config__surrogate_info_type

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__crypto_replace_ffx_fpe_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__date_shift_config__context

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__date_shift_config__crypto_key__kms_wrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__date_shift_config__crypto_key__transient

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__date_shift_config__crypto_key__unwrapped

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__date_shift_config__crypto_key

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__date_shift_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__fixed_size_bucketing_config__lower_bound__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__fixed_size_bucketing_config__lower_bound__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__fixed_size_bucketing_config__lower_bound

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__fixed_size_bucketing_config__upper_bound__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__fixed_size_bucketing_config__upper_bound__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__fixed_size_bucketing_config__upper_bound

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__fixed_size_bucketing_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__redact_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__replace_config__new_value__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__replace_config__new_value__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__replace_config__new_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__replace_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__replace_dictionary_config__word_list

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__replace_dictionary_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation__time_part_config

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations__primitive_transformation

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__field_transformations

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__record_suppressions__condition__expressions__conditions__conditions__field

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__record_suppressions__condition__expressions__conditions__conditions__value__date_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__record_suppressions__condition__expressions__conditions__conditions__value__time_value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__record_suppressions__condition__expressions__conditions__conditions__value

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__record_suppressions__condition__expressions__conditions__conditions

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__record_suppressions__condition__expressions__conditions

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__record_suppressions__condition__expressions

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__record_suppressions__condition

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations__record_suppressions

type google_data_loss_prevention_deidentify_template__deidentify_config__record_transformations

type google_data_loss_prevention_deidentify_template__deidentify_config

type google_data_loss_prevention_deidentify_template__timeouts
type google_data_loss_prevention_deidentify_template

val google_data_loss_prevention_deidentify_template :
  ?description:string prop ->
  ?display_name:string prop ->
  ?id:string prop ->
  ?template_id:string prop ->
  ?timeouts:google_data_loss_prevention_deidentify_template__timeouts ->
  parent:string prop ->
  deidentify_config:
    google_data_loss_prevention_deidentify_template__deidentify_config
    list ->
  string ->
  unit
