(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_dataproc_cluster__cluster_config__autoscaling_config

type google_dataproc_cluster__cluster_config__auxiliary_node_groups__node_group__node_group_config__accelerators

type google_dataproc_cluster__cluster_config__auxiliary_node_groups__node_group__node_group_config__disk_config

type google_dataproc_cluster__cluster_config__auxiliary_node_groups__node_group__node_group_config

type google_dataproc_cluster__cluster_config__auxiliary_node_groups__node_group

type google_dataproc_cluster__cluster_config__auxiliary_node_groups

type google_dataproc_cluster__cluster_config__dataproc_metric_config__metrics

type google_dataproc_cluster__cluster_config__dataproc_metric_config
type google_dataproc_cluster__cluster_config__encryption_config
type google_dataproc_cluster__cluster_config__endpoint_config

type google_dataproc_cluster__cluster_config__gce_cluster_config__node_group_affinity

type google_dataproc_cluster__cluster_config__gce_cluster_config__reservation_affinity

type google_dataproc_cluster__cluster_config__gce_cluster_config__shielded_instance_config

type google_dataproc_cluster__cluster_config__gce_cluster_config
type google_dataproc_cluster__cluster_config__initialization_action
type google_dataproc_cluster__cluster_config__lifecycle_config

type google_dataproc_cluster__cluster_config__master_config__accelerators

type google_dataproc_cluster__cluster_config__master_config__disk_config

type google_dataproc_cluster__cluster_config__master_config
type google_dataproc_cluster__cluster_config__metastore_config

type google_dataproc_cluster__cluster_config__preemptible_worker_config__disk_config

type google_dataproc_cluster__cluster_config__preemptible_worker_config__instance_flexibility_policy__instance_selection_list

type google_dataproc_cluster__cluster_config__preemptible_worker_config__instance_flexibility_policy__instance_selection_results = {
  machine_type : string prop;  (** machine_type *)
  vm_count : float prop;  (** vm_count *)
}

type google_dataproc_cluster__cluster_config__preemptible_worker_config__instance_flexibility_policy

type google_dataproc_cluster__cluster_config__preemptible_worker_config

type google_dataproc_cluster__cluster_config__security_config__kerberos_config

type google_dataproc_cluster__cluster_config__security_config
type google_dataproc_cluster__cluster_config__software_config

type google_dataproc_cluster__cluster_config__worker_config__accelerators

type google_dataproc_cluster__cluster_config__worker_config__disk_config

type google_dataproc_cluster__cluster_config__worker_config
type google_dataproc_cluster__cluster_config
type google_dataproc_cluster__timeouts

type google_dataproc_cluster__virtual_cluster_config__auxiliary_services_config__metastore_config

type google_dataproc_cluster__virtual_cluster_config__auxiliary_services_config__spark_history_server_config

type google_dataproc_cluster__virtual_cluster_config__auxiliary_services_config

type google_dataproc_cluster__virtual_cluster_config__kubernetes_cluster_config__gke_cluster_config__node_pool_target__node_pool_config__autoscaling

type google_dataproc_cluster__virtual_cluster_config__kubernetes_cluster_config__gke_cluster_config__node_pool_target__node_pool_config__config

type google_dataproc_cluster__virtual_cluster_config__kubernetes_cluster_config__gke_cluster_config__node_pool_target__node_pool_config

type google_dataproc_cluster__virtual_cluster_config__kubernetes_cluster_config__gke_cluster_config__node_pool_target

type google_dataproc_cluster__virtual_cluster_config__kubernetes_cluster_config__gke_cluster_config

type google_dataproc_cluster__virtual_cluster_config__kubernetes_cluster_config__kubernetes_software_config

type google_dataproc_cluster__virtual_cluster_config__kubernetes_cluster_config

type google_dataproc_cluster__virtual_cluster_config
type google_dataproc_cluster

val google_dataproc_cluster :
  ?graceful_decommission_timeout:string prop ->
  ?id:string prop ->
  ?labels:(string * string prop) list ->
  ?project:string prop ->
  ?region:string prop ->
  ?timeouts:google_dataproc_cluster__timeouts ->
  name:string prop ->
  cluster_config:google_dataproc_cluster__cluster_config list ->
  virtual_cluster_config:
    google_dataproc_cluster__virtual_cluster_config list ->
  string ->
  unit
