(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

[@@@ocaml.warning "-33-27-26"]

open! Tf.Prelude

type google_endpoints_service__timeouts = {
  create : string option; [@option]  (** create *)
  delete : string option; [@option]  (** delete *)
  update : string option; [@option]  (** update *)
}
[@@deriving yojson_of]
(** google_endpoints_service__timeouts *)

type google_endpoints_service__apis__methods = {
  name : string;  (** name *)
  request_type : string;  (** request_type *)
  response_type : string;  (** response_type *)
  syntax : string;  (** syntax *)
}
[@@deriving yojson_of]

type google_endpoints_service__apis = {
  methods : google_endpoints_service__apis__methods list;
      (** methods *)
  name : string;  (** name *)
  syntax : string;  (** syntax *)
  version : string;  (** version *)
}
[@@deriving yojson_of]

type google_endpoints_service__endpoints = {
  address : string;  (** address *)
  name : string;  (** name *)
}
[@@deriving yojson_of]

type google_endpoints_service = {
  grpc_config : string option; [@option]
      (** The full text of the Service Config YAML file (Example located here). If provided, must also provide protoc_output_base64. open_api config must not be provided. *)
  openapi_config : string option; [@option]
      (** The full text of the OpenAPI YAML configuration as described here. Either this, or both of grpc_config and protoc_output_base64 must be specified. *)
  protoc_output_base64 : string option; [@option]
      (** The full contents of the Service Descriptor File generated by protoc. This should be a compiled .pb file, base64-encoded. *)
  service_name : string;
      (** The name of the service. Usually of the form $apiname.endpoints.$projectid.cloud.goog. *)
  timeouts : google_endpoints_service__timeouts option;
}
[@@deriving yojson_of]
(** google_endpoints_service *)

let google_endpoints_service ?grpc_config ?openapi_config
    ?protoc_output_base64 ?timeouts ~service_name __resource_id =
  let __resource_type = "google_endpoints_service" in
  let __resource =
    {
      grpc_config;
      openapi_config;
      protoc_output_base64;
      service_name;
      timeouts;
    }
  in
  Resource.add ~type_:__resource_type ~id:__resource_id
    (yojson_of_google_endpoints_service __resource);
  ()
