(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_access_context_manager_access_levels__access_levels__basic__conditions__device_policy__os_constraints

type google_access_context_manager_access_levels__access_levels__basic__conditions__device_policy

type google_access_context_manager_access_levels__access_levels__basic__conditions__vpc_network_sources__vpc_subnetwork

type google_access_context_manager_access_levels__access_levels__basic__conditions__vpc_network_sources

type google_access_context_manager_access_levels__access_levels__basic__conditions

type google_access_context_manager_access_levels__access_levels__basic

type google_access_context_manager_access_levels__access_levels__custom__expr

type google_access_context_manager_access_levels__access_levels__custom

type google_access_context_manager_access_levels__access_levels
type google_access_context_manager_access_levels__timeouts
type google_access_context_manager_access_levels

val google_access_context_manager_access_levels :
  ?id:string prop ->
  ?timeouts:google_access_context_manager_access_levels__timeouts ->
  parent:string prop ->
  access_levels:
    google_access_context_manager_access_levels__access_levels list ->
  string ->
  unit
