(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_datastream_stream__backfill_all__mysql_excluded_objects__mysql_databases__mysql_tables__mysql_columns

type google_datastream_stream__backfill_all__mysql_excluded_objects__mysql_databases__mysql_tables

type google_datastream_stream__backfill_all__mysql_excluded_objects__mysql_databases

type google_datastream_stream__backfill_all__mysql_excluded_objects

type google_datastream_stream__backfill_all__oracle_excluded_objects__oracle_schemas__oracle_tables__oracle_columns

type google_datastream_stream__backfill_all__oracle_excluded_objects__oracle_schemas__oracle_tables

type google_datastream_stream__backfill_all__oracle_excluded_objects__oracle_schemas

type google_datastream_stream__backfill_all__oracle_excluded_objects

type google_datastream_stream__backfill_all__postgresql_excluded_objects__postgresql_schemas__postgresql_tables__postgresql_columns

type google_datastream_stream__backfill_all__postgresql_excluded_objects__postgresql_schemas__postgresql_tables

type google_datastream_stream__backfill_all__postgresql_excluded_objects__postgresql_schemas

type google_datastream_stream__backfill_all__postgresql_excluded_objects

type google_datastream_stream__backfill_all
type google_datastream_stream__backfill_none

type google_datastream_stream__destination_config__bigquery_destination_config__single_target_dataset

type google_datastream_stream__destination_config__bigquery_destination_config__source_hierarchy_datasets__dataset_template

type google_datastream_stream__destination_config__bigquery_destination_config__source_hierarchy_datasets

type google_datastream_stream__destination_config__bigquery_destination_config

type google_datastream_stream__destination_config__gcs_destination_config__avro_file_format

type google_datastream_stream__destination_config__gcs_destination_config__json_file_format

type google_datastream_stream__destination_config__gcs_destination_config

type google_datastream_stream__destination_config

type google_datastream_stream__source_config__mysql_source_config__exclude_objects__mysql_databases__mysql_tables__mysql_columns

type google_datastream_stream__source_config__mysql_source_config__exclude_objects__mysql_databases__mysql_tables

type google_datastream_stream__source_config__mysql_source_config__exclude_objects__mysql_databases

type google_datastream_stream__source_config__mysql_source_config__exclude_objects

type google_datastream_stream__source_config__mysql_source_config__include_objects__mysql_databases__mysql_tables__mysql_columns

type google_datastream_stream__source_config__mysql_source_config__include_objects__mysql_databases__mysql_tables

type google_datastream_stream__source_config__mysql_source_config__include_objects__mysql_databases

type google_datastream_stream__source_config__mysql_source_config__include_objects

type google_datastream_stream__source_config__mysql_source_config

type google_datastream_stream__source_config__oracle_source_config__drop_large_objects

type google_datastream_stream__source_config__oracle_source_config__exclude_objects__oracle_schemas__oracle_tables__oracle_columns

type google_datastream_stream__source_config__oracle_source_config__exclude_objects__oracle_schemas__oracle_tables

type google_datastream_stream__source_config__oracle_source_config__exclude_objects__oracle_schemas

type google_datastream_stream__source_config__oracle_source_config__exclude_objects

type google_datastream_stream__source_config__oracle_source_config__include_objects__oracle_schemas__oracle_tables__oracle_columns

type google_datastream_stream__source_config__oracle_source_config__include_objects__oracle_schemas__oracle_tables

type google_datastream_stream__source_config__oracle_source_config__include_objects__oracle_schemas

type google_datastream_stream__source_config__oracle_source_config__include_objects

type google_datastream_stream__source_config__oracle_source_config__stream_large_objects

type google_datastream_stream__source_config__oracle_source_config

type google_datastream_stream__source_config__postgresql_source_config__exclude_objects__postgresql_schemas__postgresql_tables__postgresql_columns

type google_datastream_stream__source_config__postgresql_source_config__exclude_objects__postgresql_schemas__postgresql_tables

type google_datastream_stream__source_config__postgresql_source_config__exclude_objects__postgresql_schemas

type google_datastream_stream__source_config__postgresql_source_config__exclude_objects

type google_datastream_stream__source_config__postgresql_source_config__include_objects__postgresql_schemas__postgresql_tables__postgresql_columns

type google_datastream_stream__source_config__postgresql_source_config__include_objects__postgresql_schemas__postgresql_tables

type google_datastream_stream__source_config__postgresql_source_config__include_objects__postgresql_schemas

type google_datastream_stream__source_config__postgresql_source_config__include_objects

type google_datastream_stream__source_config__postgresql_source_config
type google_datastream_stream__source_config
type google_datastream_stream__timeouts
type google_datastream_stream

val google_datastream_stream :
  ?customer_managed_encryption_key:string ->
  ?desired_state:string ->
  ?id:string ->
  ?labels:(string * string) list ->
  ?project:string ->
  ?timeouts:google_datastream_stream__timeouts ->
  display_name:string ->
  location:string ->
  stream_id:string ->
  backfill_all:google_datastream_stream__backfill_all list ->
  backfill_none:google_datastream_stream__backfill_none list ->
  destination_config:
    google_datastream_stream__destination_config list ->
  source_config:google_datastream_stream__source_config list ->
  string ->
  unit
