(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_network_services_edge_cache_service__log_config
type google_network_services_edge_cache_service__routing__host_rule

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__header_action__request_header_to_add

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__header_action__request_header_to_remove

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__header_action__response_header_to_add

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__header_action__response_header_to_remove

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__header_action

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__match_rule__header_match

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__match_rule__query_parameter_match

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__match_rule

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__route_action__cdn_policy__add_signatures

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__route_action__cdn_policy__cache_key_policy

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__route_action__cdn_policy__signed_token_options

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__route_action__cdn_policy

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__route_action__cors_policy

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__route_action__url_rewrite

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__route_action

type google_network_services_edge_cache_service__routing__path_matcher__route_rule__url_redirect

type google_network_services_edge_cache_service__routing__path_matcher__route_rule

type google_network_services_edge_cache_service__routing__path_matcher
type google_network_services_edge_cache_service__routing
type google_network_services_edge_cache_service__timeouts
type google_network_services_edge_cache_service

val google_network_services_edge_cache_service :
  ?description:string ->
  ?disable_http2:bool ->
  ?edge_security_policy:string ->
  ?edge_ssl_certificates:string list ->
  ?labels:(string * string) list ->
  ?ssl_policy:string ->
  ?timeouts:google_network_services_edge_cache_service__timeouts ->
  name:string ->
  log_config:
    google_network_services_edge_cache_service__log_config list ->
  routing:google_network_services_edge_cache_service__routing list ->
  string ->
  unit
