(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

[@@@ocaml.warning "-33-27-26"]

open! Tf.Prelude

type google_vertex_ai_featurestore_entitytype__monitoring_config__categorical_threshold_config = {
  value : float prop;
      (** Specify a threshold value that can trigger the alert. For categorical feature, the distribution distance is calculated by L-inifinity norm. Each feature must have a non-zero threshold if they need to be monitored. Otherwise no alert will be triggered for that feature. The default value is 0.3. *)
}
[@@deriving yojson_of]
(** Threshold for categorical features of anomaly detection. This is shared by all types of Featurestore Monitoring for categorical features (i.e. Features with type (Feature.ValueType) BOOL or STRING). *)

type google_vertex_ai_featurestore_entitytype__monitoring_config__import_features_analysis = {
  anomaly_detection_baseline : string prop option; [@option]
      (** Defines the baseline to do anomaly detection for feature values imported by each [entityTypes.importFeatureValues][] operation. The value must be one of the values below:
* LATEST_STATS: Choose the later one statistics generated by either most recent snapshot analysis or previous import features analysis. If non of them exists, skip anomaly detection and only generate a statistics.
* MOST_RECENT_SNAPSHOT_STATS: Use the statistics generated by the most recent snapshot analysis if exists.
* PREVIOUS_IMPORT_FEATURES_STATS: Use the statistics generated by the previous import features analysis if exists. *)
  state : string prop option; [@option]
      (** Whether to enable / disable / inherite default hebavior for import features analysis. The value must be one of the values below:
* DEFAULT: The default behavior of whether to enable the monitoring. EntityType-level config: disabled.
* ENABLED: Explicitly enables import features analysis. EntityType-level config: by default enables import features analysis for all Features under it.
* DISABLED: Explicitly disables import features analysis. EntityType-level config: by default disables import features analysis for all Features under it. *)
}
[@@deriving yojson_of]
(** The config for ImportFeatures Analysis Based Feature Monitoring. *)

type google_vertex_ai_featurestore_entitytype__monitoring_config__numerical_threshold_config = {
  value : float prop;
      (** Specify a threshold value that can trigger the alert. For numerical feature, the distribution distance is calculated by Jensen–Shannon divergence. Each feature must have a non-zero threshold if they need to be monitored. Otherwise no alert will be triggered for that feature. The default value is 0.3. *)
}
[@@deriving yojson_of]
(** Threshold for numerical features of anomaly detection. This is shared by all objectives of Featurestore Monitoring for numerical features (i.e. Features with type (Feature.ValueType) DOUBLE or INT64). *)

type google_vertex_ai_featurestore_entitytype__monitoring_config__snapshot_analysis = {
  disabled : bool prop option; [@option]
      (** The monitoring schedule for snapshot analysis. For EntityType-level config: unset / disabled = true indicates disabled by default for Features under it; otherwise by default enable snapshot analysis monitoring with monitoringInterval for Features under it. *)
  monitoring_interval_days : float prop option; [@option]
      (** Configuration of the snapshot analysis based monitoring pipeline running interval. The value indicates number of days. The default value is 1.
If both FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval_days and [FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval][] are set when creating/updating EntityTypes/Features, FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval_days will be used. *)
  staleness_days : float prop option; [@option]
      (** Customized export features time window for snapshot analysis. Unit is one day. The default value is 21 days. Minimum value is 1 day. Maximum value is 4000 days. *)
}
[@@deriving yojson_of]
(** The config for Snapshot Analysis Based Feature Monitoring. *)

type google_vertex_ai_featurestore_entitytype__monitoring_config = {
  categorical_threshold_config :
    google_vertex_ai_featurestore_entitytype__monitoring_config__categorical_threshold_config
    list;
  import_features_analysis :
    google_vertex_ai_featurestore_entitytype__monitoring_config__import_features_analysis
    list;
  numerical_threshold_config :
    google_vertex_ai_featurestore_entitytype__monitoring_config__numerical_threshold_config
    list;
  snapshot_analysis :
    google_vertex_ai_featurestore_entitytype__monitoring_config__snapshot_analysis
    list;
}
[@@deriving yojson_of]
(** The default monitoring configuration for all Features under this EntityType.

If this is populated with [FeaturestoreMonitoringConfig.monitoring_interval] specified, snapshot analysis monitoring is enabled. Otherwise, snapshot analysis monitoring is disabled. *)

type google_vertex_ai_featurestore_entitytype__timeouts = {
  create : string prop option; [@option]  (** create *)
  delete : string prop option; [@option]  (** delete *)
  update : string prop option; [@option]  (** update *)
}
[@@deriving yojson_of]
(** google_vertex_ai_featurestore_entitytype__timeouts *)

type google_vertex_ai_featurestore_entitytype = {
  description : string prop option; [@option]
      (** Optional. Description of the EntityType. *)
  featurestore : string prop;
      (** The name of the Featurestore to use, in the format projects/{project}/locations/{location}/featurestores/{featurestore}. *)
  id : string prop option; [@option]  (** id *)
  labels : (string * string prop) list option; [@option]
      (** A set of key/value label pairs to assign to this EntityType.


**Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
Please refer to the field 'effective_labels' for all of the labels present on the resource. *)
  name : string prop option; [@option]
      (** The name of the EntityType. This value may be up to 60 characters, and valid characters are [a-z0-9_]. The first character cannot be a number. *)
  monitoring_config :
    google_vertex_ai_featurestore_entitytype__monitoring_config list;
  timeouts :
    google_vertex_ai_featurestore_entitytype__timeouts option;
}
[@@deriving yojson_of]
(** google_vertex_ai_featurestore_entitytype *)

let google_vertex_ai_featurestore_entitytype ?description ?id ?labels
    ?name ?timeouts ~featurestore ~monitoring_config __resource_id =
  let __resource_type = "google_vertex_ai_featurestore_entitytype" in
  let __resource =
    {
      description;
      featurestore;
      id;
      labels;
      name;
      monitoring_config;
      timeouts;
    }
  in
  Resource.add ~type_:__resource_type ~id:__resource_id
    (yojson_of_google_vertex_ai_featurestore_entitytype __resource);
  ()
