(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_compute_region_url_map__default_route_action__cors_policy

type google_compute_region_url_map__default_route_action__fault_injection_policy__abort

type google_compute_region_url_map__default_route_action__fault_injection_policy__delay__fixed_delay

type google_compute_region_url_map__default_route_action__fault_injection_policy__delay

type google_compute_region_url_map__default_route_action__fault_injection_policy

type google_compute_region_url_map__default_route_action__request_mirror_policy

type google_compute_region_url_map__default_route_action__retry_policy__per_try_timeout

type google_compute_region_url_map__default_route_action__retry_policy
type google_compute_region_url_map__default_route_action__timeout
type google_compute_region_url_map__default_route_action__url_rewrite

type google_compute_region_url_map__default_route_action__weighted_backend_services__header_action__request_headers_to_add

type google_compute_region_url_map__default_route_action__weighted_backend_services__header_action__response_headers_to_add

type google_compute_region_url_map__default_route_action__weighted_backend_services__header_action

type google_compute_region_url_map__default_route_action__weighted_backend_services

type google_compute_region_url_map__default_route_action
type google_compute_region_url_map__default_url_redirect
type google_compute_region_url_map__host_rule
type google_compute_region_url_map__path_matcher__default_url_redirect

type google_compute_region_url_map__path_matcher__path_rule__route_action__cors_policy

type google_compute_region_url_map__path_matcher__path_rule__route_action__fault_injection_policy__abort

type google_compute_region_url_map__path_matcher__path_rule__route_action__fault_injection_policy__delay__fixed_delay

type google_compute_region_url_map__path_matcher__path_rule__route_action__fault_injection_policy__delay

type google_compute_region_url_map__path_matcher__path_rule__route_action__fault_injection_policy

type google_compute_region_url_map__path_matcher__path_rule__route_action__request_mirror_policy

type google_compute_region_url_map__path_matcher__path_rule__route_action__retry_policy__per_try_timeout

type google_compute_region_url_map__path_matcher__path_rule__route_action__retry_policy

type google_compute_region_url_map__path_matcher__path_rule__route_action__timeout

type google_compute_region_url_map__path_matcher__path_rule__route_action__url_rewrite

type google_compute_region_url_map__path_matcher__path_rule__route_action__weighted_backend_services__header_action__request_headers_to_add

type google_compute_region_url_map__path_matcher__path_rule__route_action__weighted_backend_services__header_action__response_headers_to_add

type google_compute_region_url_map__path_matcher__path_rule__route_action__weighted_backend_services__header_action

type google_compute_region_url_map__path_matcher__path_rule__route_action__weighted_backend_services

type google_compute_region_url_map__path_matcher__path_rule__route_action

type google_compute_region_url_map__path_matcher__path_rule__url_redirect

type google_compute_region_url_map__path_matcher__path_rule

type google_compute_region_url_map__path_matcher__route_rules__header_action__request_headers_to_add

type google_compute_region_url_map__path_matcher__route_rules__header_action__response_headers_to_add

type google_compute_region_url_map__path_matcher__route_rules__header_action

type google_compute_region_url_map__path_matcher__route_rules__match_rules__header_matches__range_match

type google_compute_region_url_map__path_matcher__route_rules__match_rules__header_matches

type google_compute_region_url_map__path_matcher__route_rules__match_rules__metadata_filters__filter_labels

type google_compute_region_url_map__path_matcher__route_rules__match_rules__metadata_filters

type google_compute_region_url_map__path_matcher__route_rules__match_rules__query_parameter_matches

type google_compute_region_url_map__path_matcher__route_rules__match_rules

type google_compute_region_url_map__path_matcher__route_rules__route_action__cors_policy

type google_compute_region_url_map__path_matcher__route_rules__route_action__fault_injection_policy__abort

type google_compute_region_url_map__path_matcher__route_rules__route_action__fault_injection_policy__delay__fixed_delay

type google_compute_region_url_map__path_matcher__route_rules__route_action__fault_injection_policy__delay

type google_compute_region_url_map__path_matcher__route_rules__route_action__fault_injection_policy

type google_compute_region_url_map__path_matcher__route_rules__route_action__request_mirror_policy

type google_compute_region_url_map__path_matcher__route_rules__route_action__retry_policy__per_try_timeout

type google_compute_region_url_map__path_matcher__route_rules__route_action__retry_policy

type google_compute_region_url_map__path_matcher__route_rules__route_action__timeout

type google_compute_region_url_map__path_matcher__route_rules__route_action__url_rewrite

type google_compute_region_url_map__path_matcher__route_rules__route_action__weighted_backend_services__header_action__request_headers_to_add

type google_compute_region_url_map__path_matcher__route_rules__route_action__weighted_backend_services__header_action__response_headers_to_add

type google_compute_region_url_map__path_matcher__route_rules__route_action__weighted_backend_services__header_action

type google_compute_region_url_map__path_matcher__route_rules__route_action__weighted_backend_services

type google_compute_region_url_map__path_matcher__route_rules__route_action

type google_compute_region_url_map__path_matcher__route_rules__url_redirect

type google_compute_region_url_map__path_matcher__route_rules
type google_compute_region_url_map__path_matcher
type google_compute_region_url_map__test
type google_compute_region_url_map__timeouts
type google_compute_region_url_map

val google_compute_region_url_map :
  ?default_service:string ->
  ?description:string ->
  ?timeouts:google_compute_region_url_map__timeouts ->
  name:string ->
  default_route_action:
    google_compute_region_url_map__default_route_action list ->
  default_url_redirect:
    google_compute_region_url_map__default_url_redirect list ->
  host_rule:google_compute_region_url_map__host_rule list ->
  path_matcher:google_compute_region_url_map__path_matcher list ->
  test:google_compute_region_url_map__test list ->
  string ->
  unit
