(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type google_compute_security_policy__adaptive_protection_config__layer_7_ddos_defense_config

type google_compute_security_policy__adaptive_protection_config

type google_compute_security_policy__advanced_options_config__json_custom_config

type google_compute_security_policy__advanced_options_config
type google_compute_security_policy__recaptcha_options_config

type google_compute_security_policy__rule__header_action__request_headers_to_adds

type google_compute_security_policy__rule__header_action
type google_compute_security_policy__rule__match__config
type google_compute_security_policy__rule__match__expr
type google_compute_security_policy__rule__match

type google_compute_security_policy__rule__rate_limit_options__ban_threshold

type google_compute_security_policy__rule__rate_limit_options__exceed_redirect_options

type google_compute_security_policy__rule__rate_limit_options__rate_limit_threshold

type google_compute_security_policy__rule__rate_limit_options
type google_compute_security_policy__rule__redirect_options
type google_compute_security_policy__rule
type google_compute_security_policy__timeouts
type google_compute_security_policy

val google_compute_security_policy :
  ?description:string prop ->
  ?id:string prop ->
  ?project:string prop ->
  ?type_:string prop ->
  ?timeouts:google_compute_security_policy__timeouts ->
  name:string prop ->
  adaptive_protection_config:
    google_compute_security_policy__adaptive_protection_config list ->
  advanced_options_config:
    google_compute_security_policy__advanced_options_config list ->
  recaptcha_options_config:
    google_compute_security_policy__recaptcha_options_config list ->
  rule:google_compute_security_policy__rule list ->
  string ->
  unit
