(* DO NOT EDIT, GENERATED AUTOMATICALLY *)

open! Tf.Prelude

type digitalocean_app__spec__alert
type digitalocean_app__spec__database
type digitalocean_app__spec__domain
type digitalocean_app__spec__env
type digitalocean_app__spec__function__alert
type digitalocean_app__spec__function__cors__allow_origins
type digitalocean_app__spec__function__cors
type digitalocean_app__spec__function__env
type digitalocean_app__spec__function__git
type digitalocean_app__spec__function__github
type digitalocean_app__spec__function__gitlab
type digitalocean_app__spec__function__log_destination__datadog
type digitalocean_app__spec__function__log_destination__logtail
type digitalocean_app__spec__function__log_destination__papertrail
type digitalocean_app__spec__function__log_destination
type digitalocean_app__spec__function__routes
type digitalocean_app__spec__function
type digitalocean_app__spec__ingress__rule__component
type digitalocean_app__spec__ingress__rule__cors__allow_origins
type digitalocean_app__spec__ingress__rule__cors
type digitalocean_app__spec__ingress__rule__match__path
type digitalocean_app__spec__ingress__rule__match
type digitalocean_app__spec__ingress__rule__redirect
type digitalocean_app__spec__ingress__rule
type digitalocean_app__spec__ingress
type digitalocean_app__spec__job__alert
type digitalocean_app__spec__job__env
type digitalocean_app__spec__job__git
type digitalocean_app__spec__job__github
type digitalocean_app__spec__job__gitlab
type digitalocean_app__spec__job__image__deploy_on_push
type digitalocean_app__spec__job__image
type digitalocean_app__spec__job__log_destination__datadog
type digitalocean_app__spec__job__log_destination__logtail
type digitalocean_app__spec__job__log_destination__papertrail
type digitalocean_app__spec__job__log_destination
type digitalocean_app__spec__job
type digitalocean_app__spec__service__alert
type digitalocean_app__spec__service__cors__allow_origins
type digitalocean_app__spec__service__cors
type digitalocean_app__spec__service__env
type digitalocean_app__spec__service__git
type digitalocean_app__spec__service__github
type digitalocean_app__spec__service__gitlab
type digitalocean_app__spec__service__health_check
type digitalocean_app__spec__service__image__deploy_on_push
type digitalocean_app__spec__service__image
type digitalocean_app__spec__service__log_destination__datadog
type digitalocean_app__spec__service__log_destination__logtail
type digitalocean_app__spec__service__log_destination__papertrail
type digitalocean_app__spec__service__log_destination
type digitalocean_app__spec__service__routes
type digitalocean_app__spec__service
type digitalocean_app__spec__static_site__cors__allow_origins
type digitalocean_app__spec__static_site__cors
type digitalocean_app__spec__static_site__env
type digitalocean_app__spec__static_site__git
type digitalocean_app__spec__static_site__github
type digitalocean_app__spec__static_site__gitlab
type digitalocean_app__spec__static_site__routes
type digitalocean_app__spec__static_site
type digitalocean_app__spec__worker__alert
type digitalocean_app__spec__worker__env
type digitalocean_app__spec__worker__git
type digitalocean_app__spec__worker__github
type digitalocean_app__spec__worker__gitlab
type digitalocean_app__spec__worker__image__deploy_on_push
type digitalocean_app__spec__worker__image
type digitalocean_app__spec__worker__log_destination__datadog
type digitalocean_app__spec__worker__log_destination__logtail
type digitalocean_app__spec__worker__log_destination__papertrail
type digitalocean_app__spec__worker__log_destination
type digitalocean_app__spec__worker
type digitalocean_app__spec
type digitalocean_app__timeouts
type digitalocean_app

type t = private {
  active_deployment_id : string prop;
  created_at : string prop;
  default_ingress : string prop;
  id : string prop;
  live_url : string prop;
  project_id : string prop;
  updated_at : string prop;
  urn : string prop;
}

val digitalocean_app :
  ?id:string prop ->
  ?project_id:string prop ->
  ?timeouts:digitalocean_app__timeouts ->
  spec:digitalocean_app__spec list ->
  string ->
  t
